### PR TITLE
remove Changelog Section from comments

### PR DESCRIPTION
**Pull request by larsgrefer**
see also: #672

### CODE REVIEW

**Comment by larsgrefer** [comment]
@SecUpwN please review and merge

**Comment by SecUpwN** [comment]
@larsgrefer, I've had a look and agree with what you've done. Yet I wonder why you only removed the changelog section and not Issues, TODO and whatever else is left in those files? Or what's the plan here? :)

**Comment by larsgrefer** [comment]
@SecUpwN I am not sure if some of the Issues/Todos might be important and should be converted to github issues as suggested here: https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/672#issuecomment-165847558

**Comment by SecUpwN** [comment]
>I am not sure if some of the Issues/Todos might be important and should be converted to github issues as suggested

@larsgrefer, yes, we should follow that suggestion. Did you crawl through the whole code to remove changelog stuff, or shall I continue reviewing all files after merging this?

**Pull request merged**
