### PR TITLE
simplify the credits view

### LINKED ISSUE #523: CreditsRollView.java uses or overrides a deprecated API.
Above mentioned line is viewed at building the app.
I think we should remove the RollView and make it a normal scrollable view or popup as the rest.
I also think the RollView is really bad to read...

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/23593274-creditsrollview-java-uses-or-overrides-a-deprecated-api?utm_campaign=plugin&utm_content=tracker%2F565750&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F565750&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by larsgrefer**
- just use a simple dialog
- remove the star-wars gimmick
- fix #523 

Maybe @agilob or @DJaeger want to review

### CODE REVIEW

**Comment by SecUpwN** [comment]
Too bad that this neeat little gimmick is now vanishing, but I guess our app is growning up with your great work here, @larsgrefer. Would you please add a screenshot here as well so that I can view it?

**Comment by larsgrefer** [comment]
screenshot_20151225-234803
screenshot_20151225-234814

**Comment by SecUpwN** [comment]
@larsgrefer, is above list sccrollable? Not sure if you can center everything for a slightly better look?

**Comment by larsgrefer** [comment]
@SecUpwN Yes, its scrollable

I think instead of centering everything we should just remove the ASCII-art in order to get a better look

**Comment by larsgrefer** [comment]
@SecUpwN Why
- is the credits-text an asset instead of an string resource and why
- does it contain manual line-breaks with `\n`

**Comment by SecUpwN** [comment]
@larsgrefer, because this is what was required to make it look better with the star wars theme and in fact was converted from a string resource into an asset. If you see potential for improvements, please add them.

**Pull request merged**
