### PR TITLE
added toast cancel on new toast

### PR DESCRIPTION
**Pull request by DJaeger**
Should also show the toast at the correct position.
https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/403#issuecomment-114845124

### CODE REVIEW

**Comment by SecUpwN** [comment]
Would love to merge this. Could you please digg the [Travis CI failure](https://travis-ci.org/SecUpwN/Android-IMSI-Catcher-Detector/builds/68161891#L2135-L2163)?

**Comment by SecUpwN** [comment]
@DJaeger, seems almost cleared up. Have a look at [this](https://travis-ci.org/SecUpwN/Android-IMSI-Catcher-Detector/builds/68174469#L2132-L2142).

**Comment by SecUpwN** [comment]
Another one bites the [dust](https://travis-ci.org/SecUpwN/Android-IMSI-Catcher-Detector/builds/68177809#L2126-L2130)... :P

**Comment by DJaeger** [comment]
It's not easy with Travis CI as only debugger available...

**Comment by DJaeger** [comment]
It's working :-D

**Pull request merged**
