### PR TITLE
From RootTools to RootShell

### PR DESCRIPTION
**Pull request by Stericson**
Removed RootTools source.

Added RootShell source.

Removed dependency on RootTools, added dependency on RootShell.

Fixed code to account for RootShell, added note about the potentially improper use of RootShell.

The code will work fine, but ideally shell commands should either be done in a shell or commandWait should be removed and the callback methods should be used to continue the flow of execution.

### CODE REVIEW

**Comment by SecUpwN** [comment]
Thank you for rocking this, @Stericson! Could you please check if you can fix this Travis CI failure?

>* What went wrong:
>A problem occurred configuring project ':app'.
> Cannot evaluate module RootShell : Configuration with name 'default' not found.

**Comment by Stericson** [comment]
Yep, I'm looking into it...not sure why it's failing. Builds fine for me...

**Comment by SecUpwN** [comment]
If you clikc on the little red `x`, you can see the Travis CI logfile, which in this case tells:

>A problem occurred configuring project ':app'.
> Cannot evaluate module RootShell : Configuration with name 'default' not found.

**Comment by Stericson** [comment]
This is driving me crazy...

The build file is there...and it's not empty...

"Evaluating project ':third_party:RootShell' using empty build file."

**Comment by E3V3A** [comment]
Looks like our old friend `The command "./gradlew connectedAndroidTest" exited with 1.` is back from the grave. Didn't we just have this problem a few weeks ago?

**Comment by E3V3A** [comment]
[Here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/236) with same issue.

**Comment by Stericson** [comment]
HAH, I fixed it....Apparently upper case modules and directories are a no no...

**Comment by Stericson** [comment]
^^ over 9000 commits later :D

**Comment by E3V3A** [comment]
@SecUpwN You wanna commit this?

**Comment by E3V3A** [comment]
@Stericson  Uppercase as in naming convention? That is really a WTF!

**Comment by SecUpwN** [comment]
>Looks like our old friend `The command "./gradlew connectedAndroidTest" exited with 1.` is back from the grave. Didn't we just have this problem a few weeks ago?

Yes, but apparently you did not look at the logfiles, @E3V3A. If Travis CI exits with `1`, that means it failed, `0` means success. When pressing the small red `x`, the log tells what is actually wrong. And beck then the errors came from insufficient memory for the builds, now we run on the new container-build infrastructure and thus also on faster machines running multiple threads to finish faster.

>HAH, I fixed it....Apparently upper case modules and directories are a no no...

@Stericson, huge **THANKS** for standing through all this shizzle! Happy to have you here. :+1:

In fact, I would like to wait until #263 is finished until merging this. After that, I will update the versioning in `AndroidManifest.xml` and `CHANGELOG` before actually compiling a new version.

**Pull request merged**
