### PR TITLE
SMS Detection Implementation

### PR DESCRIPTION
**Pull request by banjaxbanjo**
Implementation of SMS detection.

For this to work more effectively on samsung devices please set debug to high on the menu at:
`*#9900#` or `*#*#9900#*#*`

* Detects Type 0 and silent voice sms on Samsung S5
* Detects Silent Voice on Sony Xperia J.

Advanced users can set strings if they know what they are doing and also if you find a string that is detecting type 0 or silentvoice sms please contact @SecUpwN with the string.

### CODE REVIEW

**Comment by SecUpwN** [comment]
This is **AWESOME** @banjaxbanjo, thank you so much!

I guess this is the solution you've been working on to solve #69? Shall I add your instructions above to our WIKI page on [Special SMS](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Special-SMS)? Before adding this, I'd like @DimaKoz and @tobykurien to have a quick look at this.

**Comment by agilob** [comment]
Just a few comments:

I think it's bad practise to write such code:
```
+        try {
+            if (smsdetector.getSmsDetectionState()) {
+                smsdetector.stopSmsDetection();
+            }
+        }catch (Exception ee){Log.e(TAG,"Error stopping sms detection\n"+ee.toString());}
```
From logs we know nothing about the exception, it would be better to change it to:
```
catch (NPE e) {
e.printStackTrace();
} catch (AnotherException e) {
e.printStackTrace();
}
``` 

2 Newly created classes/files don't have licence. You added your copyright statement, but without license, so this will violate GPLv3. Other files have header:
```
/* Android IMSI-Catcher Detector | (c) AIMSICD Privacy Project
 * -----------------------------------------------------------
 * LICENSE:  http://git.io/vJaf6 | TERMS:  http://git.io/vJMf5
 * -----------------------------------------------------------
 */
```

3 smsdetection/AdvancedUserActivity.java
I have no idea why there is try|catch in onCreate, no information about type of exception, no comments about catch{} block?
3 1 `}catch (Exception ee){}` how do we know something went bad? what kind of exception is that?

4 smsdetection/SmsDetector.java
`public void checkForSilentSms(String[] progress)` starts on line 192 and ends on 339 ;_;
It would be good to remove unused code completely.

**Comment by banjaxbanjo** [comment]
Hey I am not a professional programmer m8 and haven't a clue about licenses so if you could make a PR to fix those changes Id be greatful, try catches are they so the app doesnt die I put in alot just to be on safe side so feel free to remove what you want m8. Yep forgot about check for silent sms code that can be removed also cheers.

Sent from Yahoo Mail on Android

**Comment by banjaxbanjo** [comment]
Might be ugly code but it works I will need to go college to start writing proper code but this is the best I can do for what I know atm☺

**Comment by SecUpwN** [comment]
Thanks for your feedback, @agilob! I know that the code by @banjaxbanjo might not be perfect (yet), but hey, this is an open source project and anyone is welcome to improve it. @He3556 just toldd me that he is trying to reach @andr3jx so that he can have a look too before we merge this. I hope it's no problem for you that we're having a closer look at all this before merging, @banjaxbanjo. It's a whole bunch of code. Would you mind adding [proper code comments](https://source.android.com/source/code-style.html#java-style-rules) in the places where other developers may have problems finding their way?

**Comment by banjaxbanjo** [comment]
Ideally I would have loved to comment more m8 but I don't have the time thats why I pushed it last night. Wont be at computer for 2-3 weeks.

**Comment by SecUpwN** [comment]
>Ideally I would have loved to comment more m8 but I don't have the time thats why I pushed it last night.

No problem, I see that you've put a lot of work into it. If we merge your pull request, it would be great if you could come back after these 2 - 3 weeks and continue to improve the code +  comments, will ya? ;-)

**Comment by banjaxbanjo** [comment]
Will do m8 no problem there, Just want to give people something useful, its more for the end user atm they wont see the inner workings of this.

**Comment by andr3jx** [comment]
@SecUpwN Ok, I had a look. All I can say is: Test it and test it again.

**Comment by SecUpwN** [comment]
>All I can say is: Test it and test it again.

Thanks @andr3jx. I will merge this pull request **after** our release tonight so that people do not complain about "stuff not working". Feel invited improving the code after we have merged it tomorrow.

**Pull request merged**
