### PR TITLE
Add support for uploading exact BTS GPS locations draft

### PR DESCRIPTION
**Pull request by ziem**
#590 This pull request contains:
- adding markers to map (long press)
- dragging (long press + move)
- click

I also created empty methods: `loadUserDefinedCoordinates`, `saveUserDefinedCoordinates` and `updateUserDefinedCoordinates`. Second and third method is invoked in right place so you can fill them with database operations and everything should work.

### CODE REVIEW

**Comment by agilob** [comment]
So I can manually change location of cells and mess up their database? Most people will use it for that purpose. We know that, right?

**Comment by SecUpwN** [comment]
Thanks for your PR @ziem, would you please find out what the merge conflicts? Did you update your fork prior crafting this?

**Comment by ziem** [comment]
Fork synced. Is there anything else I need to do?

**Comment by SecUpwN** [comment]
Do you see the commands when pressing `Use the command line`?

**Comment by ziem** [comment]
I updated my PR. Above you can see my last commit:
> Fork sync

**Comment by SecUpwN** [comment]
@smarek, would you help @ziem resolving the merge conflicts, please?

**Comment by smarek** [comment]
@SecUpwN Since it's draft, how do you want to merge it? Because either we are interested in the feature allowing users to spoil the OCID database, we heavily rely on, and in that case we can use the feature branch to test it and merge it when it's complete feature (not a draft), or we don't want this feature, and I see no point in merging it.

@ziem sorry, you have to rebase your feature commits on top of current development branch state, not include all the changes between your development and current state within PR. 
Do some reading here: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

And my personal insight is that you could go with `git rebase origin/development` (if origin is this repository), but do some back ups first and be prepared to solve the merge conflicts.

Maybe most easy, non-git, way to do it correctly, would be for you to copy&paste your code from https://github.com/ziem/Android-IMSI-Catcher-Detector/commit/b47589acdc779098127cec5f95d77cbe36fda4fa having opened latest *development* branch and create this PR again when your changes will be on top in `git log`

**Comment by banjaxbanjo** [comment]
I don't know if this is off topic but you could put a filter to only log a BTS if the signal eqaul MAX rssi/dbm value this way you know its at least close to the BTS, or before upload parse the data to make sure the rssi is max value and only add to the csv file if value is max.

We log keep logging the BTS as normal but if the rssi > than the rssi stored in the database then update previous record with new gps coors & new rssi level if they are valid.

You won't need to use this option then of adding personal markers which is not a good idea as @agliob has said and would only take one person maybe an IMSIC group to mess up the OCID database.

**Comment by agilob** [comment]
@smarek or create new branch from current origin/master and `git patch` using this https://patch-diff.githubusercontent.com/raw/SecUpwN/Android-IMSI-Catcher-Detector/pull/645.patch, I do it most often, it's faster and don't have to merge conflicts o/

**Comment by smarek** [comment]
@agilob since the file was touched with 75b6e40b45f3748e057989d96c15144eb906dfab which is not on master yet, i don't think that'll work nicely as PR against development

@banjaxbanjo good point :+1:

**Comment by ziem** [comment]
@smarek I won't be able to continue working on this feature. I created pull request upon @SecUpwN's request with everything (not too much) I did few weeks ago. Feel free to close this PR if you find it unneeded.

**Comment by SecUpwN** [comment]
@ziem, I hope you don't get discourage because of this stuff here. Should we close it, @smarek?

**Comment by smarek** [comment]
@SecUpwN depends on how the discussion on #590 will turn out, if we really want this feature, I'll rebase it and propose in my own PR finished (this is really just a draft)

**Comment by SecUpwN** [comment]
@smarek, please add some thoughts to that discussion so that we may find a solution there. Thanks!

**Pull request closed without merging**
