### PR TITLE
479 notification material design

### PR DESCRIPTION
**Pull request by Ph1b**
This is related to #479 

Changes:
* Use a large icon for the notification so the icons colors are being used
* Removed unnecessary code and prevent a guaranteed NPE
* Improved code style and readability

### CODE REVIEW

**Comment by SecUpwN** [comment]
Whoa, since when have you been working on this, @Ph1b? Looks like a freakload of work, so **THANK YOU** for getting involved and feel warmly welcome in our privacy project! Please try to fix the following:

```JAVA
* What went wrong:

A problem occurred configuring project ':app'.
> failed to find target android-22 : /usr/local/android-sdk
```

**Comment by E3V3A** [comment]
Hi @Ph1b Thanks for joining us and contributing!

1. Can you please reformat your code to our standards and remove your HTML tags in it. 
2. Also some more descriptive PR comments would be greatly appreciated, especially for such major code changes. E.g. in `Removed unnecessary null check` which removes a significant chunk of code and many important comments we would like to keep.
3. You also say `Removed unnecessary checks` and go on removing the neighboring cells check. Why?
4. And `Reduced visibilities` describe changing from *public* to *private*...
5. Very few of you changes seem to have anything to do with the "notification material design"...

I can go on, but I'd rather have both a second and third opinion on this one, before letting this pass...

**Comment by E3V3A** [comment]
@DJaeger @banjaxbanjo Can you please look at this ASAP!

**Comment by Ph1b** [comment]
Sorry if this caused confusion.

1. These are not my html tags. My ide just moved some code and removed whitespaces.
2. I neither added nor removed any comments. Its mostly just removed unnecessary stuff like [here](https://github.com/Ph1b/Android-IMSI-Catcher-Detector/commit/ccaca1044fa4a15e8626d6a2fc7a3f0c817d048a#diff-9386af9ad86862d793ce1c985d760babL407).
3. Which neighboring checks were removed?

Really sorry if this caused so much confusion, for me it was mainly a small cleanup.

**Comment by Ph1b** [comment]
Travis failed because it doesn't have the latest android sdk.

**Comment by SecUpwN** [comment]
>Really sorry if this caused so much confusion, for me it was mainly a small cleanup.

Don't worry. Are you able to remove the HTML tags? Just wait for @E3V3A adding more suggestions. :)

>Travis failed because it doesn't have the latest android sdk.

That really sucks. Should I file and Issue on their repo? Wonder how they maintain their service..

**Comment by Ph1b** [comment]
What do you mean with html tags? Can you point me to a line?

**Comment by SecUpwN** [comment]
>What do you mean with html tags? Can you point me to a line?

To be honest, I don't see any. But I am sure @E3V3A will link the relevant lines for you.

**Comment by E3V3A** [comment]
ALL the comment formatting is FUBAR. And look for `<p/>`...

**Comment by E3V3A** [comment]
*White space* should not be removed, but replaced with space to keep original formatting.

**Comment by SecUpwN** [comment]
@Ph1b, why did you close this now? Throwing away your work? :(

**Comment by E3V3A** [comment]
@Ph1b Yeah, I didn't mean to be discouraging either, but we've spent too much time trying to document...blah blah. 

Just make another PR and disable the white space removal in your IDE so to leave comments as they are. As for the neighbor cell thing, I suppose a `null` is not the same as `0`, so this need to be tested on many different devices, as these items are often rather corrupted. As someone else said, if it ain't broke, don't fix it. We've had various "cleanup" and "refactoring" events here lately, that have totally messed up some stuff, introducing a load of weird bugs (we're still trying to recover from), just because of lack of insight. We just wanna prevent this from happening again.

**Pull request closed without merging**
