### PR TITLE
Credits dialog bug fix

### LINKED ISSUE #803: CREDITS are not completely showing anymore
>Thank you for your feedback! Please add below details so that we can help you a bit faster.

---

- [x] **I have reviewed and accepted the [guidelines for contributing](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x] **I have searched the [open Issues](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [x] **I have read the notes on [debugging](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

---

When pressing `CREDITS`, not even half of the list of our `CREDITS` from [credits.xml](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/AIMSICD/src/main/res/values/credits.xml) is being shown. 

* `AIMSICD` version (see the `About` screen): Always using latest Buildozer build

---

Just press `CREDITS` in the `About` screen and see how few people are being shown. Furthermore, I'd like the `CREDITS` to see an improvement in terms of looks: How about cerntering the text and enabling users to actually press the links (for example to Github profiles) contained in that file? I just want this to look and feel neat, I feel our contributors deserve a place where they can be proud even when they already left our project.

---

This bug may have been introduced with #787 by @VladThodo.

### PR DESCRIPTION
**Pull request by VladThodo**
This fixes #803 
I'm verry sorry for the bug , I should have used percentages in the animation file  from the begining 
Also I'm working on making the links to work

### CODE REVIEW

**Comment by SecUpwN** [comment]
>I'm verry sorry for the bug , I should have used percentages in the animation file from the begining

No rpoblem, it happens to the best of us. Thanks for being so quick on a fix. Before I merge this: Have you had a look at the mentioned visual improvements (centering, clickable links) yet? Guess that might be good.

**Comment by VladThodo** [comment]
@SecUpwN  I have centered the text and the title. I will add all the commits when  I will get the links working

**Comment by VladThodo** [comment]
@SecUpwN  Done ;)

**Comment by SecUpwN** [comment]
Thanks! Can you add a screenshot of how it looks now before I merge this and possibly complain again? :)

**Comment by VladThodo** [comment]
Of course @SecUpwN  , here you have it 
screenshot_2016-02-28-12-50-19

**Comment by SecUpwN** [comment]
>Of course @SecUpwN , here you have it

Approved! Wonderful work. Thank you very much! :+1:

**Pull request merged**
