### PR TITLE
Switch to IDLE when attack detection is turned off

### LINKED ISSUE #716: Status not switching to IDLE when disabling detection
Taken from https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/pull/711#issuecomment-167716002, our app currently shows status `OK` or `MEDIUM` even when disabling detections by pressing `Toggle Attack Detection` in `Navigation Drawer`. It should switch to `IDLE`.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29452238-status-not-switching-to-idle-when-disabling-detection?utm_campaign=plugin&utm_content=tracker%2F565750&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F565750&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by VladThodo**
Attempt to fix #716 and make the status switch to IDLE when the `Toggle attack detection` is turned off. :-)

### CODE REVIEW

**Comment by SecUpwN** [comment]
@VladThodo, thanks for coding this bugfix! In your pull request description, dou you actually mean that it switches to `IDLE` when `Toggle attack detection` has been turned **off** (which would be the correct case)?

**Comment by VladThodo** [comment]
@SecUpwN Yeah

**Comment by SecUpwN** [comment]
@VladThodo, please see if you can fix [these checkstyle errors](https://travis-ci.org/SecUpwN/Android-IMSI-Catcher-Detector/builds/113180464#L1850-L2262) so that I can merge this.

**Comment by VladThodo** [comment]
@SecUpwN  Errors are fixed

**Comment by SecUpwN** [comment]
>Errors are fixed

Perfect. Approved!

**Comment by SecUpwN** [comment]
Approved!

**Pull request merged**
