### PR TITLE
Delete split.rb

### PR DESCRIPTION
**Pull request by larsgrefer**
@SecUpwN Is this file still needed?

### CODE REVIEW

**Comment by SecUpwN** [comment]
This is a ruby script to split opencellid CSV files into separate files for each MCC.
How would OpenCellID CSV files be split when deleting that file, @tobykurien?

**Comment by larsgrefer** [comment]
Where and when is this file used?

**Comment by SecUpwN** [comment]
>Where and when is this file used?

To be honest, it doesn't seem to be used in the current code. I guess Toby just put it there so that we can use the script to split the CSV files for each MCC when we want to - so likely not used within our app. I'll send him a quick message so that he can reply here and will wait for his response before merging this PR.

**Comment by tobykurien** [comment]
Yup you can delete it. I believe the idea was to have smaller JSON files to load depending on your area, rather than the entire opencellid database.

**Comment by SecUpwN** [comment]
@larsgrefer, let me know here if I still shall merge this after you've read above clarification. Thanks.

**Comment by larsgrefer** [comment]
Yes, please merge

**Pull request merged**
