### PR TITLE
Add debugging code to dump full sms in pdu format

### PR DESCRIPTION
**Pull request by banjaxbanjo**
Think this code will be useful to see the full  sms in pdu Hex format and will be easier to parse the created string, plus can be sent to debugging output on app. Comment out if not needed:)

### CODE REVIEW

**Comment by SecUpwN** [comment]
Thank you very much for your PR, @banjaxbanjo! @tobykurien and @E3V3A, please have a look at this if we can merge it without braking our `development` branch. Otherwise please give some instructions if @banjaxbanjo needs to craft a fresh PR to our `development` branch and if I shall close this.

**Comment by tobykurien** [comment]
Looks good. I would prefer if there was a try-catch around the string building, so that if there is an error, it doesn't crash the app when an SMS comes in. Not critical, but that could happen.

**Comment by banjaxbanjo** [comment]
Ah sorry try catch a good idea better safe than sorry will update asap. Will work on a parsing function or class to parse the pdu fields smsc tp-dcs tp-mti tp-pid so its easier to pinpoint a particular element like tp-mti.
Thanks

**Comment by E3V3A** [comment]
@banjaxbanjo  Thanks for your PRs! They're much appreciated, but please use the `development` branch from now on, and also ensure you've actually tried and compiled the code before you make a PR for it.

**Comment by banjaxbanjo** [comment]
@E3V3A Hey E.V.A, I've only run this code in a dummy app but will compile dev app for future PR so not to cause any errors.;-).

**Pull request merged**
