### PR TITLE
Recheck cell after OCID download

### PR DESCRIPTION
**Pull request by DJaeger**
Fix for #558.

### CODE REVIEW

**Comment by DJaeger** [comment]
Will fix this later

**Comment by E3V3A** [comment]
So what are we doing? 
Why is this failing? 

```
:app:compileReleaseJava/home/travis/build/SecUpwN/Android-IMSI-Catcher-Detector/app/src/main/java/com/SecUpwN/AIMSICD/utils/RequestTask.java:322: error: cannot find symbol
        tm = (TelephonyManager) context.getSystemService(Context.TELEPHONY_SERVICE);
        ^
  symbol:   variable tm
  location: class RequestTask

/home/travis/build/SecUpwN/Android-IMSI-Catcher-Detector/app/src/main/java/com/SecUpwN/AIMSICD/utils/RequestTask.java:322: error: cannot find symbol
        tm = (TelephonyManager) context.getSystemService(Context.TELEPHONY_SERVICE);
                                ^
  symbol:   variable context
  location: class RequestTask

/home/travis/build/SecUpwN/Android-IMSI-Catcher-Detector/app/src/main/java/com/SecUpwN/AIMSICD/utils/RequestTask.java:323: error: cannot find symbol
        CellLocation cellLocation = tm.getCellLocation();
                                    ^
  symbol:   variable tm
  location: class RequestTask

Note: /home/travis/build/SecUpwN/Android-IMSI-Catcher-Detector/app/src/main/java/com/SecUpwN/AIMSICD/fragments/CreditsRollView.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
 FAILED
```

**Comment by E3V3A** [comment]
@SecUpwN  Why does the Travis icon report build passed, when in fact it has failed?

**Comment by SecUpwN** [comment]
>Why does the Travis icon report build passed, when in fact it has failed?

Because the PR has not been merged yet. PRs are being checked separately.

**Comment by E3V3A** [comment]
Ah, thanks.

**Comment by E3V3A** [comment]
@DJaeger  Please re-make this PR as it doesn't play nice with us...

**Comment by DJaeger** [comment]
Will make new one

**Pull request closed without merging**
