### PR TITLE
479 notification material design fixed # 2

### PR DESCRIPTION
**Pull request by Ph1b**
Pull request #526 reduced to a minimum for #479.

### CODE REVIEW

**Comment by SecUpwN** [comment]
Thank you very much for cleaning it up! I will launch the Travis-CI build manually again in a second...

**Comment by E3V3A** [comment]
@SecUpwN I suppose its hard to keep up with Google vomiting updates over us nearly every damn day. Which is a good reason not to keep up to date. I simply started to refuse to update Android Studio for all this dumbness. Make life much easier...

**Comment by E3V3A** [comment]
@SecUpwN  Does this also affect Buildozer? (If yes, it's a no go.) 

@Ph1b Is updating the dependencies required for this to work?

**Comment by E3V3A** [comment]
@SecUpwN Is it possible to merge only part of a PR? (Trying to avoid the "Updated Dependencies".)

**Comment by SecUpwN** [comment]
>Does this also affect Buildozer? (If yes, it's a no go, as we wouldn't be able to test it.)

@E3V3A, no, Buildozer should work just fine.

> Is it possible to merge only part of a PR? (Trying to avoid the "Updated Dependencies".)

Nope. But I guess the current failing check might be due to `$ANDROID_TARGET` not being set correctly in our `.travis.yml`, I guess - and *not* due to updated dependencies this time. @Ph1b, please issue the suggested command `android list targets` to get the correct target ID. Hope it helps.

**Comment by E3V3A** [comment]
You can't merge this, beacuse I just made some changes to CellTracker and MiscUtils. That's why I asked about just partial merges.

**Comment by SecUpwN** [comment]
>We'll have to re-implement the changes above and close this PR again. Sorry for this mess....

We don't have to. Changes can be pulled into @Ph1b's fork and be added to this PR.

**Comment by E3V3A** [comment]
@SecUpwN Is somebody actually doing this, or am I waiting for nothing?

**Comment by E3V3A** [comment]
@SecUpwN Ok, So when is that going to happen?

**Comment by SecUpwN** [comment]
>Ok, So when is that going to happen?

It will happen once @Ph1b will be online and decides to updater this PR based upon your changes.

**Comment by E3V3A** [comment]
We can probably close this now. I just made this replacement, without the updated libs: 75ec459ff4920b251c1a3ceb0c95900f265f4a98

**Comment by E3V3A** [comment]
@Ph1b  I've re-implemented pretty much everything (apart the code re-organization and formatting) from your PR. Thanks a lot for your great effort, we really appreciate it!

**Pull request closed without merging**
