### PR TITLE
Fixes CellTracker RequestTask etc..

### PR DESCRIPTION
**Pull request by banjaxbanjo**
Ok This fixes issue where CellTracker/RequestTask where out of date, they now are same as more recent by @E3V3A 10 days ago and have my changes merged.

Changed index around in AIMSICDDbAdapter that should sort Avg_Signal/Range not being in right order.(Cant check this as the most recent version of the project is not working well with OCID server)
Seems to be timing out W/System.err﹕ java.net.SocketTimeoutException

Update OCID server seems back in action and range /signal is corrected in DBV layout

### CODE REVIEW

**Comment by E3V3A** [comment]
@DJaeger Can you link to the snippet you're talking about?
I just hit the merge button...

**Comment by DJaeger** [comment]
@E3V3A: Why do you merge, if there seems somthing to be wrong?
I mean https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/src/main/java/com/SecUpwN/AIMSICD/utils/RequestTask.java#L354-360

**Comment by E3V3A** [comment]
Because your comment appeared after I hit the merge button.

**Comment by E3V3A** [comment]
Ok, latest build now crashes after trying to download OCID...
@DJaeger Should I revert?

**Comment by E3V3A** [comment]
In addition, I expect anyone who make a PR, to actually test it before making it. It's not the commiters job to test the PRs...

**Comment by DJaeger** [comment]
The mentioned part does not be relevant to OCID download, only upload/restore.
The issue you have sounds like #543, which does not depend on this merge.

**Comment by E3V3A** [comment]
It does depend on this merge, since the build before was working for me, and now it's not.

**Comment by DJaeger** [comment]
Mhm, for me it is working.
Also #543 seems to be fixed for me.

**Comment by E3V3A** [comment]
@banjaxbanjo  You still didn't fix CellTracker!! Compare to: https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/d590e2ea774750d12177d9151d12ddf86b4b8b42

**Comment by banjaxbanjo** [comment]
@E3V3A omg that popup was added by me in request task because half the time it doesn't tell when complete I didnt skip anything and the classes aren't going back to original they are adding stuff that was missing and have my changes the original claases dont work with new database. Cmon

**Comment by banjaxbanjo** [comment]
@E3V3A Can you tell me your problem with CellTracker and show me where what is missing?

**Comment by E3V3A** [comment]
If you can be so kind to actually click on the links I provide, it is clearly highlighted in green! All the comments and minor changes I've added in that commit are gone in yours. This is exactly the same link I gave you [2 days](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/548#issue-95010923) ago.

**Comment by DJaeger** [comment]
@banjaxbanjo: That's correct, what @E3V3A says, that you missed that commit.
@E3V3A: please try a clean installation of the last build before this merge to check if the crash occures.

**Pull request merged**
