### PR TITLE
Some UX Enhancements

### PR DESCRIPTION
**Pull request by d-mariano**
Some UX Enhancements:  If there is still a conflict, I will update my repo and apply manual changes, and then make another PR.

### CODE REVIEW

**Comment by d-mariano** [comment]
I forgot to contain a conflict it seems.

**Comment by SecUpwN** [comment]
@d-mariano, do you know why I cannot merge this yet? Anything I can help you with?

**Comment by d-mariano** [comment]
I am currently merging your master into my master (I made a backup of my changes in-case this goes south) I will then try and merge into your repo

**Comment by SecUpwN** [comment]
Perfect! Thanks for keeping the Pimp-Hand strong!

**Comment by SecUpwN** [comment]
@d-mariano, I have merged all previous commits from the old `DevTest` branch, please try to re-sync and push one more thing so that this PR gets possible! Also, future development shall take place on branch `development`. Thank you!

**Comment by d-mariano** [comment]
I'm getting the same conflicts, unfortunately I don't have time to go through them all at the moment.

**Comment by SecUpwN** [comment]
Take your time! As you can see, anything you push will be added here. As soon as you've resolved everything, I will merge this to `master`. Future development shall take place in `development` to avoid a broken `master`.

**Comment by d-mariano** [comment]
This push contains changes from development branch.  Should I PR to development?

**Comment by SecUpwN** [comment]
@E3V3A, please tell me how to proceed here. The PR is ready to merge and I am not quite sure if I should first pull everything from `development` and `eventlog-branch` and then merge it, or mrge it right away and wait for the other branches to get in sync again? I'd like to avoid breaking further commits.

**Comment by E3V3A** [comment]
@SecUpwN  Please see chat room discussion. Then remove this confusing PR as @d-mariano  will redo the whole thing with another GitHub suitable tool, when his time allows.

**Pull request closed without merging**
