### PR TITLE
moved more strings to xml files, read more...

### PR DESCRIPTION
**Pull request by agilob**
more strings can be translated
some cosmetic changes in java source code
merged helpers to strings.xml
improved Polish translation
removed unused imports (done automatically by android studio)

sorry for such long commit with so many changes, I didn't plan it.

### CODE REVIEW

**Comment by SecUpwN** [comment]
Thanks for proposing this pull request and solving the conflict I was just going to write about! Question: Will this pull request ease up translations a bit? I'd like the translations to be as convenient as possible.

**Comment by agilob** [comment]
helpers conflicted because helpers.xml was updated after i removed it. solved by updating strings and removing helpers again.

**Comment by agilob** [comment]
helpers was merged to strings.xml, don't merge to master yet, I need to test something.

**Comment by SecUpwN** [comment]
>helpers was merged to strings.xml, don't merge to master yet, I need to test something.

I will **only** merge to `master` when we release a fresh version. Everything else is taking place on our `development` branch, that is why we have it. So don't worry. I have just invited you to our [Buildozer](https://buildozer.io/) account, it builds a fresh APK upon `development` branch changes.

**Comment by agilob** [comment]
Noooo dont merge yet :<<

**Pull request merged**
