### PR TITLE
Menu improved

### PR DESCRIPTION
**Pull request by DimaKoz**
The menu has been reordered and renamed by issue SecUpwN/Android-IMSI-Catcher-Detector#258
Description of help and button for that were added. @E3V3A @SecUpwN menu now looks like this:

device-2015-04-25-232530
device-2015-04-25-232548

### CODE REVIEW

**Comment by SecUpwN** [comment]
Thank you for your hard work on this, @DimaKoz! I have a few questions before merging this:

1. You closed #389 due to the missing library. Is there a new one available as asked in [here(]https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/pull/389#issuecomment-96387026)?
2. Since @agilob has done a great job adding translations, are these Info-Items added to `strings.xml`?
3. Please as always increase the version like you did before and I'll be happy to merge.

**Comment by DimaKoz** [comment]
>Please as always increase the version like you did before and I'll be happy to merge.

with pleasure
I need the rules by which we increase the version of the application, and which I will follow

>1. You closed #389

I redid it there https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/pull/391

>@agilob has done a great job adding translations. Are these Info-Items added to strings.xml?

I fully agree with you - it was great job
but I've noticed some errors when  'lintVitalRelease' task in Gradle running and fixed them:

>:app:processReleaseManifest UP-TO-DATE
/Users/bull/repo_IMSI_Catcher_Detector/app/build/intermediates/res/release/values-pl/values.xml:90: warning: string 'hsdpa' marked untranslatable but exists in locale 'pl'
....
/Users/bull/repo_IMSI_Catcher_Detector/app/src/main/res/values/arrays.xml:9: Error: "pref_ui_icons_values" is not translated in "pl" (Polish) [MissingTranslation]
    <string-array name="pref_ui_icons_values">
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
14 errors, 0 warnings
:app:lintVitalRelease

**Comment by DimaKoz** [comment]
@SecUpwN I also propose to add the execution of this test ('lintVitalRelease' task) to our Travis

**Comment by SecUpwN** [comment]
>I need the rules by which we increase the version of the application, and which I will follow.

The rules have been described in #365. Basically you just increase the build number (the `XX` in `*-alpha-bXX`) in `android:versionName` when changing code on the `development` branch and when I release our app, I'll be increasing the `android:versionCode` as well as number before the `alpha`).

>I also propose to add the execution of this test ('lintVitalRelease' task) to our Travis.

Yes, please do so, just add it to this pull request!

**Pull request merged**
