### PR TITLE
CellInfoFragment refresh button changed to swiperefreshlayout

### LINKED ISSUE #783: All current Cell Details
Sony Xperia V lt25i,Unlocked,Rooted CyanogenMod 12.1 NEO-tsubasa  Lollipop 5.1.1 
AIMSICD Version unspecified-normal, Version Nummer T-1643.(WIP TEST RELEASE v0.1.41-alpha)

If I download OCID Data from MAP view the downloading marker (circle) keeps turning after
the downloading has finished. It stops if I leave the page & return back.

If I try to go to "All current Cell Details" in the menu nothing happens, seems like it's not
possible to return to "All current Cell Details" from any place..

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/31136501-all-current-cell-details?utm_campaign=plugin&utm_content=tracker%2F565750&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F565750&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by tt3mm**
~~Edit by **SecUpwN**: I guess this should fix #783.~~

### CODE REVIEW

**Comment by SecUpwN** [comment]
Thanks for your work here, @tt3mm. Please fix [these checkstyle violations](https://travis-ci.org/SecUpwN/Android-IMSI-Catcher-Detector/builds/112164876#L1850-L2258) so that we can merge it.

**Comment by tt3mm** [comment]
Nope, but if there is 2 refreshing action then they should work the same way

**Comment by SecUpwN** [comment]
Seems like a few more things have to be tackled until we can merge this:

```
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve io.freefair:gradle-plugins:2.0.0-beta4.
     Required by:
         :Android-IMSI-Catcher-Detector:unspecified
      > Could not resolve io.freefair:gradle-plugins:2.0.0-beta4.
         > Could not get resource 'https://jitpack.io/io/freefair/gradle-plugins/2.0.0-beta4/gradle-plugins-2.0.0-beta4.pom'.
            > Could not GET 'https://jitpack.io/io/freefair/gradle-plugins/2.0.0-beta4/gradle-plugins-2.0.0-beta4.pom'. Received status code 521 from server: Origin Down

```

**Comment by tt3mm** [comment]
for me ./gradlew build check runs without error, also I could download from that link.
Could you try again the build? It could been overloaded or something.

**Comment by SecUpwN** [comment]
>Could you try again the build? It could been overloaded or something.

Just a second, I'll do a relaunch via the Travis-CI interface. Status should update then.

**Comment by SecUpwN** [comment]
Approved!

**Pull request merged**
