### PR TITLE
783 all current cell details bugfix

### LINKED ISSUE #783: All current Cell Details
Sony Xperia V lt25i,Unlocked,Rooted CyanogenMod 12.1 NEO-tsubasa  Lollipop 5.1.1 
AIMSICD Version unspecified-normal, Version Nummer T-1643.(WIP TEST RELEASE v0.1.41-alpha)

If I download OCID Data from MAP view the downloading marker (circle) keeps turning after
the downloading has finished. It stops if I leave the page & return back.

If I try to go to "All current Cell Details" in the menu nothing happens, seems like it's not
possible to return to "All current Cell Details" from any place..

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/31136501-all-current-cell-details?utm_campaign=plugin&utm_content=tracker%2F565750&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F565750&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by tt3mm**
In the DeviceFragment I added the SwipeRefreshLayout, and moved the logic from the NavDraver there to fix #783. One thing thats bugging me, is the AnimationManager.
I don't see any animation in the updateUI, however it seems everything is being called.

### CODE REVIEW

**Comment by SecUpwN** [comment]
Thanks! Is this the same pull request as #799? if so, would you like me to close the other one?

**Comment by tt3mm** [comment]
Nope! In #799 I just changed a refresh button in "Current Threat Level" to SwipeResfreshLayout. Close both.

**Comment by SecUpwN** [comment]
>Close both.

Why close both?

**Comment by tt3mm** [comment]
I mean merge both :D its for different screens

**Comment by SecUpwN** [comment]
>I mean merge both :D its for different screens

Approved!

**Pull request merged**
