### PR TITLE
Minor update to stop the app from crashing 

### PR DESCRIPTION
**Pull request by VladThodo**
The app was crashing when cliking the 'credits' button..

### CODE REVIEW

**Comment by larsgrefer** [comment]
can you post a stacktrace of the error you fixed?

**Comment by agilob** [comment]
`Exception ee` in a catch block is never null, some exceptions don't have message, that's why you should NEVER do `catch (Exception e)`, always catch each exception separately. Better question is what caused the exception...

**Comment by banjaxbanjo** [comment]
Hey guys I'd say it was a NPE caused by the bad while loop, Sorry about the bad error catching @agilob, I can now see why this coding would insult any programmer maintaining this code. 

#### Fix
```java
    public static String loadCredits(Context context){
        BufferedReader reader = null;
        StringBuilder buildassets = new StringBuilder();
        try{
            reader = new BufferedReader(new InputStreamReader(context.getAssets().open("CREDITS")));

            String rline;
            while ((rline = reader.readLine()) != null ) {
                buildassets.append(rline.replace("'","\\'").replace("\\n","") + "\n");
            }

        } catch (IOException ee) {
            log.error(ee.getMessage());
        } finally {
            if(reader != null) {
                try {
                    reader.close();
                } catch (IOException ee) {
                    log.error(ee.getMessage());
                }
            }
        }
        return (buildassets.toString().isEmpty())
                ? "Error Loading Credits"
                : buildassets.toString();

    }
```
#### Optional if min API is 19
```java
    //API 19
    public static String setAssetsString2(Context context){

        StringBuilder buildassets = new StringBuilder();
        try(BufferedReader reader = new BufferedReader(
                new InputStreamReader(context.getAssets().open("CREDITS")))){

            String rline;
            while ((rline = reader.readLine()) != null ) {
                buildassets.append(rline.replace("'","\\'").replace("\\n","") + "\n");
            }

        } catch (IOException ee) {
            log.error(ee.getMessage());
        }

        return (buildassets.toString().isEmpty())
                ? "Error Loading Credits"
                : buildassets.toString();
    }
```
#### CreditsRollActiviy.java - update
```java
        if (!mScrolling) {
            mCreditsRollView.setText(MiscUtils.loadCredits(getApplicationContext()));
            animateScroll();
        }
```

**Comment by SecUpwN** [comment]
>can you post a stacktrace of the error you fixed?

@VladThodo, please reply to this question. @banjaxbanjo, thanks for your proposed fixes!
Would you please craft separate pull requests for these things so that we can check those?

**Comment by VladThodo** [comment]
@larsgrefer , Here is the log: 
`02-13 09:02:27.222    3035-3035/com.SecUpwN.AIMSICD E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.SecUpwN.AIMSICD, PID: 3035
    java.lang.NullPointerException: println needs a message
            at android.util.Log.println_native(Native Method)
            at android.util.Log.e(Log.java:232)
            at io.freefair.android.util.logging.AndroidLogger.error(AndroidLogger.java:79)
            at com.SecUpwN.AIMSICD.utils.MiscUtils.setAssetsString(MiscUtils.java:47)
            at com.SecUpwN.AIMSICD.activities.AboutActivity$7.onClick(AboutActivity.java:137)
            at android.view.View.performClick(View.java:4438)
            at android.view.View$PerformClick.run(View.java:18422)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.main(Native Method)`

**Comment by SecUpwN** [comment]
Approved! Thanks for adding the requested Stacktrace, @VladThodo.

>@SecUpwN , wouldn't be great to make the credits dialog autoscroll?

Of course, we love pull requests! Maybe you can also fix #726?
Feel warmly invited to help us cutting down on our [current Issues](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues).

**Pull request merged**
