### PR TITLE
incremented database version

### PR DESCRIPTION
**Pull request by tobykurien**
tiny bug fix: app was crashing when I tried it, seems there were database changes but the database version was not incremented.

### CODE REVIEW

**Comment by E3V3A** [comment]
That's funny, are you on L? Never had this problem. Are you sure you wiped all the AIMSICD leftovers when you got that crash? I know Sec had a funny error when trying to just re-install app over old version without rebooting.

**Comment by SecUpwN** [comment]
Thanks for this fix, @tobykurien! When did you compile the `development` branch? We've just reverted another commit which as meant to add the `CreditsRoll` but which in fact destroyed our Travis CI builds. Please check if this fix is still useful after the revert. If it is, I'll go ahead and merge it ASAP.

**Comment by tobykurien** [comment]
@E3V3A the point is that there are releases out in the wild, and when they install the new version, their database needs to get upgraded. You wouldn't see this error if you re-installed the app after the database changes.

@SecUpwN I pulled the latest code, which does not have the creditsroll in it. So this merge should work without messing up the current state of the development branch

**Comment by E3V3A** [comment]
@tobykurien  I see, but then the question is how we wanna support this kind of updates in alpha stage. We're changing DB all the time, so does that mean we have to increment `DATABASE_VERSION` every time we make a change?

**Comment by tobykurien** [comment]
If you make the change between releases, then yes, otherwise users will keep seeing crashes.

**Comment by E3V3A** [comment]
Is there a way to automatically detect this? I suppose we could compare that value to what's in the current DB?

**Comment by tobykurien** [comment]
It's automatically handled, you just need to increment the version number, that's all. The way it's currently set up, it drops all tables and re-creates the new ones when the version number changes. This isn't ideal, but for the alpha phase, it's fine.

**Comment by E3V3A** [comment]
Or how about a settings option to always wiping all tables also when updated with same DB version? 
@He3556 Would like to have your input here. This is a no-brainer for now, but could be an improvement item for later.

**Pull request merged**
