### PR TITLE
Fix getprop for debug email

### PR DESCRIPTION
**Pull request by tobykurien**
See https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/301

### CODE REVIEW

**Comment by SecUpwN** [comment]
@tobykurien, thanks for your continued awesome work! Just one question: Since we now have a `DevTest` branch, where shall all the main development take place? There? And when shall I craft a PR to merge into `Master`? I am a little confused now, please tell me what the "best practice" is here..

**Comment by E3V3A** [comment]
@SecUpwN  I think (please correct me if wrong!) that this PR is getting merged onto "DevTest" then we can merge "DevTest" into Master when needed.

**Comment by E3V3A** [comment]
@tobykurien  Thank you again for this commit!! :dancers:

**Comment by E3V3A** [comment]
@tobykurien  Unfortunately there seem to be some regressions here. The quit button stopped working properly and take you back to the last viewed screen, while the debug log is constantly cleared missing all info, although now the getprop is working as promised... Any ideas what's going on?

**Comment by E3V3A** [comment]
Not sure what happened there, but now i can't reproduce that quit behavior. Instead I noticed that when returning from Debugging screen, the app restarts...

**Comment by d-mariano** [comment]
Is there something wrong with the quit again?  I wonder what that could be now...never a dull moment here.  I like it.  I will be busy finishing a paper today that I must have complete for tomorrow, but if I have time and we make this a new issue, I will take it upon myself to investigate after I successfully merge my recent changes.

**Comment by tobykurien** [comment]
The idea with a dev branch would be that all changes only happen on the dev branch. When you make a release, you then merge the release onto the master branch. That way, anyone checking out the master branch gets the latest release, instead of possibly buggy, unstable dev stuff.

**Comment by d-mariano** [comment]
Makes sense to me.  If we get bigger, we could throw in an Experimental
repo and be all like "Stable, Testing, Experimental"

On Wed, Jan 28, 2015 at 1:22 PM, Toby Kurien <notifications@github.com>
wrote:

> The idea with a dev branch would be that all changes only happen on the
> dev branch. When you make a release, you then merge the release onto the
> master branch. That way, anyone checking out the master branch gets the
> latest release, instead of possibly buggy, unstable dev stuff.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/pull/302#issuecomment-71887004>
> .
>



-- 
-DM

**Comment by SecUpwN** [comment]
We're currently discussing the things based on this great [GitHub workflow](http://scottchacon.com/2011/08/31/github-flow.html) article. Stay tuned!

**Pull request merged**
