### PR TITLE
Updating Russian

### PR DESCRIPTION
**Pull request by gaich**
This pull request updates the russian translation since weblate was too difficult to use for me.

### CODE REVIEW

**Comment by larsgrefer** [comment]
Thanks.

Can you @mention a second russian-speaking person which can verify your translations?

**Comment by SecUpwN** [comment]
Thanks for your work and following [my call on XDA]http://forum.xda-developers.com/showpost.php?p=65024232&postcount=2656, @gaich! I just wondeer why you did not use [weblate] to make this easier. ardg people to check this, I hope @RussianBruteForce or @geosphere will do so.

**Comment by gaich** [comment]
I explained this on xda - cannot even manage to open the translation page on Weblate, the only achievement was signing in. As for the second Russian-speaking person, I cannot recommend anyone, I am responsible for my tramslations myself and don't want some schoolboy using Google translate to correct them.

**Comment by SecUpwN** [comment]
>As for the second Russian-speaking person, I cannot recommend anyone, I am responsible for my tramslations myself and don't want some schoolboy using Google translate to correct them.

Don't worry. The people I previously linked have edited the russian translation before. Stay tuned.

**Comment by SecUpwN** [comment]
Approved!

**Pull request merged**
