### PR TITLE
Recheck cell after OCID download

### PR DESCRIPTION
**Pull request by DJaeger**
Fix for #558

### CODE REVIEW

**Comment by DJaeger** [comment]
illegal character: \160 ???
What's this?
I become mad...

**Comment by E3V3A** [comment]
yes, very weird. 
Did you try building by yourself?

**Comment by E3V3A** [comment]
@SecUpwN  What to do here? Merge anyway?

**Comment by DJaeger** [comment]
Please do not merge until have figured out what this characters are.

**Comment by E3V3A** [comment]
> char code 160 would be &nbsp;

You probably have set your file to use unicode characters. Try to convert and save your file in ASCII.

**Comment by SecUpwN** [comment]
Sorry to see you having so many troubles, @DJaeger. Don't give up, we're bearing with you! :+1:

**Pull request closed without merging**
