### PR TITLE
MapViewer fixes for #228

### PR DESCRIPTION
**Pull request by tobykurien**

### CODE REVIEW

**Comment by SecUpwN** [comment]
Oh hey, this gotta be your New Years Pull Request, huh? Many thanks, so WOW! Just a quick question before I merge this: Could you please verify if E:V:A did [this](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/463fec0c9f1dadd86ab04209ec146ab28a75e17b) right? It seems as if we now have differenmt Icon sizes in each drawable folder, not sure if that is how it's meant to be..

**Comment by tobykurien** [comment]
@SecUpwN no the icons are incorrectly sized - it looks like he just copied the same icons into all the folders. @E3V3A you need to read this https://developer.android.com/training/basics/supporting-devices/screens.html#create-bitmaps

**Comment by SecUpwN** [comment]
@tobykurien, thanks for confirming my intitial thoughts. I guess E:V:A just introduced this "hotfix" because he was annoyed of the pins being too large. Can those Icons be made generic in size?

>I just noticed and understood that since we're using an overlay (AFAIK), the icons doesn't scale down with the map when you zoom out. Thus they remain relatively huge, when zooming out. This make them look ugly and get bloated out with each other. We need to use non-overlay icons if possible.

Before merging your great pull request here, can we focus on fixing #250, please? What do I need to do really fix that Issue? I guess changing the map pins to the correct sizes for each folder isn't enough..

**Comment by tobykurien** [comment]
I don't understand what needs to be done with #250 at all. Besides the fact that the pins have now been modified, so I don't even know what the current status of pin colors is. It also mentions DBe_import, which I am not familiar with yet. Finally, I don't see how that needs to stop you merging the pull request.

**Comment by SecUpwN** [comment]
>Finally, I don't see how that needs to stop you merging the pull request.

@tobykurien, it actually doesn't. I was just thinking you could tell me what to do about #250. I will correct the pin sizes after having merged this pull request and we'll go from there what E:V:A tell me.

**Comment by E3V3A** [comment]
@tobykurien Awesome! Also, I've tried to clarify # 250 for you.

**Pull request merged**
