### PR TITLE
Remove agilob from source code

### PR DESCRIPTION
**Pull request by agilob**
Please remove me from [team list as well](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Contact). 

Thanks.

### CODE REVIEW

**Comment by SecUpwN** [comment]
May I ask what is making you leave us for good?

**Comment by agilob** [comment]
I think this project is going in a completely wrong direction than it was supposed to go and in which it **was** going before ~March 2015. I won't be needed here anymore. I'll still be browsing and reading commits like I do for many others projects. Feel free to contact me on email if you want something :)

**Comment by SecUpwN** [comment]
@agilob, I strongly disagree with that our project is moving into "wrong direction" just because we're applying some fresher UI and cleaning some cruft from the code. I fully respect your choice to leave our team, something which I really do not understand because we have not busted your bubble or hurt you otherwise. Nevertheless, please let me **CLOSE** this pull request and manually remove you from the team page, keeping you in lovely rememberance in our `CREDITS` and `CHANGELOG`. You've been part of all this, you've been of great help and I do not want you to be erased from history. Please continue to use our app even though you may not feel like you want to be part of active development any longer. Rest in peace.

**Comment by agilob** [comment]
I don't really care about the UI. If more people welcome those changes them I'm for it.

>we have not busted your bubble or hurt you otherwise

Obviousely not, I was thinking about removing myself from the projects for a long time, it's my decision, not based on your actions. It's nothing personal, never was and never will be. Personally I think you're a great project manager and you're doing good job keeping this project under development.

>please let me CLOSE this pull request and manually remove you from the team page, keeping you in lovely rememberance in our CREDITS and CHANGELOG

Sure, you're the leader here.

**Comment by SecUpwN** [comment]
>My phone is too weak to run this app, screen freezes all the time on any manual action.

There are new phones out there, you know? ;-) Thanks for telling the truth here, this makes it easier for me to get along with your decision. Don't lose your humor, man! You may delete your fork now. Farewell!

**Comment by agilob** [comment]
Yes, but I don't use phones. I don't like them. I don't want to be reached when someone else wants to reach me, I want to be contacted when I want to be in contact. Phone do exactly the opposite. They violate privacy, security, cost money and make me feel a slave. Why would anyone want it?

**Comment by banjaxbanjo** [comment]
Good point best security to avoid imsic's and 100's of other  vulnerabilities is have no phone.

**Comment by agilob** [comment]
I also don't use skype and contribute to [qtox](https://github.com/tux3/qTox) ;)

**Comment by SecUpwN** [comment]
>I also don't use skype and contribute to qtox ;)

You may find this useful: www.prism-break.org. Enjoy!

**Comment by agilob** [comment]
That's another project where you can find my commits...

**Comment by banjaxbanjo** [comment]
That's a good looking project could take off and be big, looks similar to viber if that's not an insult.

**Comment by agilob** [comment]
We're doing design and decisions on our own, not inspired by skype/viber or anything else.

**Comment by banjaxbanjo** [comment]
Well if that's true that's a good thing and unique design.

**Pull request closed without merging**
