### PR TITLE
Some UX Enhancements

### PR DESCRIPTION
**Pull request by d-mariano**
I have saved visual space by creating two columns of information on some views in the DBViewer.  I have also edited CardItemData.java and CellCardInflator.java and DbViewerFragment.java to support newly added TextViews in layouts.  These TextViews are labels for information retrieved in the DB, therefore hard coding labels in the java source is no longer required and not recommended.  With label TextViews, we can now adjust the attributes of the labels and their particular information separately.

### CODE REVIEW

**Comment by d-mariano** [comment]
Please let me know how many merge conflicts they are, if it is a big matter then I can pull from this branch and redo this changes quickly with an updated repo.

**Comment by SecUpwN** [comment]
@d-mariano, huge thanks for this pull request! Is it much that you changed? We're currently cleaning up internally, please see your E-Mails. I hope we'll be able to pull this into `DevTest` before merging to 'Master'.

**Comment by d-mariano** [comment]
It isn't a great amount.  I mostly worked with the xml's.   I'm trying to pull from your repo and merge into mine...should I not do that and wait?

**Comment by SecUpwN** [comment]
@d-mariano, have you seen your E-Mails? I am about to **DELETE* the `DevTest` branch. Would you be able to apply your changes to our `Master` (I have just synced it with `DevTest`)? I will then purge `DevTest`.

**Comment by d-mariano** [comment]
I was just reading the updates on HipChat, but I haven't seen much activity on my E-Mail.  Drop away!  I have nothing I am working on now...I was just getting myself organized this morning.

**Comment by SecUpwN** [comment]
Ok, so if I fully **DELETE** `DevTest` now, you will **NOT** lose your work? Please apply it to **MASTER** when you're done with organizing. I am re-organizing myself with this, too. Cheers!

**Comment by d-mariano** [comment]
Okay, I'll try merging what I just merged now to master.  If there are still conflicts, I will update my repo from master via pull request into mine, and then I will manually paint the changes.

**Pull request closed without merging**
