### PR TITLE
syncing development branch to master for last months changes

### PR DESCRIPTION
**Pull request by E3V3A**
Many many changes, please see individual commit comments.

### CODE REVIEW

**Comment by SecUpwN** [comment]
@E3V3A, please wait with the merge of this. I am syncing as soon as the PR of Kai (on which he is currently working) has been submitted and then I'll also sync the `CHANGELOG` before a fresh release.

**Comment by E3V3A** [comment]
Ok, but then you'll have to close this and make a new one. Make sure you post a debug-build in test room and so that we can test the app before making another PR (dev --> master). Otherwise we'll be sitting on a broken code base. This is why it's better you just merge this now. Since everything has been tested and is good to go. The rest is just development... IMHO. Seem this will cause another few days of delay... :(

**Comment by E3V3A** [comment]
@SecUpwN  Please merge!

**Comment by SecUpwN** [comment]
Thanks you for your incredible patience, @E3V3A! I will wait until the latest Travis CI build has finished and merge this down to be finally ready for the **RELEASE** that we've been aiming for so long. Cheers!

**Pull request merged**
