### PR TITLE
Master

### PR DESCRIPTION
**Pull request by elfevenfairy**

### CODE REVIEW

**Comment by freemi** [comment]
Wow this is the first time I have done a pull :)

**Comment by DJaeger** [comment]
An empty pull request?
What should this be?

**Comment by E3V3A** [comment]
This is too weird! What is this? 
@SecUpwN ?

**Comment by elfevenfairy** [comment]
Well I'm just learning I just started a few days ago I learned some of it in 20 hours so I really need to read it more I'm not just learning one thing so this the out come of it so I have been teaching myself on some of it .

**Comment by SecUpwN** [comment]
@E3V3A, I reported the guy creating this PR. Seems to be another bot.

**Pull request closed without merging**
