### PR TITLE
Improved OCID upload

### PR DESCRIPTION
**Pull request by kairenken**
I've improved the OCID upload. It's only done when new cells were collected and it's checking if http response was ok and DB-Entrys are only updated in this case.

I'm not sure if the CellTracker is the right location to start the RequestTask.

Please have a look at my pull request and give me some feedback about it.

Thank you.

### CODE REVIEW

**Comment by E3V3A** [comment]
@kairenken 
Hello Kai and Welcome! Thank you very much for trying to fix this. However, we're not able to merge your PR for some reason. I don't know why, but could be perhaps you forgot to synch with the latest (~4 days ago) developer branch commits? 

In addition there are two other problems with this upload function:
 1. Probably (as you suggested) `CellTracker` is not the right place to do this, especially since it attempts to re-download OCID data immediately after upload, which simply doesn't work and should never even be attempted.
 2. OCID upload should be done **only manually and not automatically**, which is why we commented out that code, and added some placeholders to a new upload button in the menu drawer. This need to be fixed. 

The reasoning behind this is that we do not want to accidentally upload fake BTS to OCID.
Do you think you can fix this?

**Comment by SecUpwN** [comment]
@kairenken, welcome to our project also from my side! I really enjoy that you've been digging into our code all by yourself, which is something we rarely see here (unfortunately). Also thanks for closing #333 and re-doing all the work to the correct branch. If you now continue to fix the things E:V:A just mentioned, I will pay special attention to your pull request and help you should further problems arise.

**Comment by kairenken** [comment]
Thanks for your replies I'll try to fix the merging conflicts, if it comes to trouble I'll rebase my own development to your devbranch. So see my next commit.

**Comment by kairenken** [comment]
I've added a button to manually upload local bts data. I hope the merging was correct and that I haven't missed something.

**Comment by kairenken** [comment]
Oh I've got some trouble with merging here, I don't know why. So we should use cherry pic for this commit. Sorry for the circumstances.

**Comment by SecUpwN** [comment]
@kairenken, great stuff here! Merging seems all well for me, even Travis CI plays along nicely (which is one of the important factors I always watch out for). @E3V3A, please merge if you agree. Your turn.

**Comment by kairenken** [comment]
I see lot of changes in  app/src/main/java/com/SecUpwN/AIMSICD/adapters/AIMSICDDbAdapter.java
some in  app/src/main/java/com/SecUpwN/AIMSICD/adapters/AIMSICDDbAdapter.java
and also in  app/src/main/java/com/SecUpwN/AIMSICD/utils/RequestTask.java
which were not in my intention.

**Comment by E3V3A** [comment]
@kairenken  In all honesty, I'm a bit confused to what this merge will do, since I don't see why your commit: https://github.com/kairenken/Android-IMSI-Catcher-Detector/commit/77c8591a60673baad19e3679a3f4c53f00c369c9 
is added to the PR here. It doesn't make sense, but perhaps it's just a GitHub "thing"?

**Comment by E3V3A** [comment]
@kairenken  Are you using command line *nix git or GitHub for windows client/app?

**Comment by kairenken** [comment]
I'm using command line git and meld as merge tool.

**Comment by kairenken** [comment]
maybe i'll should start with a new clean fork rebase to your devbranch and merge my changes into that one?

**Comment by SecUpwN** [comment]
@kairenken, maybe you should try [SmartGit](http://www.syntevo.com/smartgit/). I personally love it.

**Comment by E3V3A** [comment]
@kairenken 
> maybe i'll should start with a new clean fork rebase to your devbranch and merge my changes into that one?

That would be ideal, and also allow us to better track changes. Thank you for your patience.

**Comment by E3V3A** [comment]
@SecUpwN  @He3556 

Ah, I just realized something. I think the problem is that when people fork, they automatically get the `master` branch, and not the `developer` branch. (Is that correct?) If so, the setting up of [webhooks](https://developer.github.com/v3/repos/hooks/) is even more urgent.

**Comment by kairenken** [comment]
I close this pull request. Please see my new pull request #335 which is based on branch development. The problem was me committing to master branch in my fork. I tried to merge with kairenken@77c8591 but that made things just stranger instead of healing it.

**Pull request closed without merging**
