### PR TITLE
fixed default value for "start on boot" value

### PR DESCRIPTION
**Pull request by tobykurien**
As per comment in https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/246

### CODE REVIEW

**Comment by E3V3A** [comment]
Any reason we want this to start on boot on alpha edition? I certainly don't want it,  which is why i changed it earlier. Just asking.

**Comment by He3556** [comment]
This was a Bug, see https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/246 
Now the App closes when you hit close on the main menue :)

**Comment by SecUpwN** [comment]
Thanks for the pull request on this, @tobykurien! Question before merging: Does this finally fix #246?

**Comment by tobykurien** [comment]
@E3V3A the change you made introduced the bug, because you can't just change the settings.xml file, you need to change the default value in code too. So I made the change in the code.

**Comment by E3V3A** [comment]
I had no idea. So what's the point of having a settings.xml if you also need to change the code?

**Pull request merged**
