### PR TITLE
Moved Toast

### PR DESCRIPTION
**Pull request by banjaxbanjo**

### CODE REVIEW

**Comment by DJaeger** [comment]
@banjaxbanjo: You missed a line break.
Also please use our toaster class.

**Comment by E3V3A** [comment]
@DJaeger  Show where it is, and I'll fix asap.

**Comment by DJaeger** [comment]
In the middle of https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/pull/552/files#diff-8c165bf530b165dcf42db226db30e440R362
Directly before the pasted area.
Because of that the first line is shifted to much.

**Comment by E3V3A** [comment]
What about the toaster class?

**Comment by banjaxbanjo** [comment]
@E3V3A  if you are taking about this break it was here before my PR so just left as is.

```Java
              } else {
                    Helpers.msgLong(mAppContext, mAppContext.getString(R.string.error_backing_up_data));
                }
                //break;
```

**Comment by banjaxbanjo** [comment]
Are you serious?
>Directly before the pasted area. Because of that the first line is shifted to much

**Comment by banjaxbanjo** [comment]
@E3V3A I was using same popup as in backup complete as it takes such I long time you will have to literally not take you eyes off the screen not to miss the popup(Which is also showing) with this

**Comment by DJaeger** [comment]
Ok, than let the AlertDialog in.

> Directly before the pasted area. Because of that the first line is shifted to much.

Here I only speak of the missed line break.
I have linked it.
Is anyway not clear?

**Comment by E3V3A** [comment]
Not clear, what exactly should I do? 
Add the `break;` statement after the last `case` choice?

**Comment by banjaxbanjo** [comment]
@E3V3A I think he is saying that the line is tabbed not a break;

**Comment by banjaxbanjo** [comment]
Fixes tabbed line:O
```Java
            case RESTORE_DATABASE:
                if (result != null && result.equals("Successful")) {
                    Helpers.msgShort(mAppContext, mAppContext.getString(R.string.restore_database_completed));
                    Activity lActivity = getActivity();
                    
                    if(lActivity != null) {//Activity may be detached or destroyed
                        final AlertDialog.Builder builder = new AlertDialog.Builder(lActivity);
                        builder.setTitle(R.string.restore_database_completed_title).setMessage(
                                lActivity.getString(R.string.restore_database_completed));
                        builder.create().show();
                    }
                } else {
                    Helpers.msgLong(mAppContext, mAppContext.getString(R.string.error_restoring_database));
                }
                break;
```

**Pull request merged**
