### PR TITLE
Animated credits dialog

### PR DESCRIPTION
**Pull request by VladThodo**
Successor of my previous pull requests #785 and #786. Now the credits dialog scrolls automatically :-)

### CODE REVIEW

**Comment by larsgrefer** [comment]
@VladThodo Can you resolve the build errors?

**Comment by VladThodo** [comment]
@larsgrefer  I'm working on it :) I've added the needed file,but I'm still getting an errorr `Checkstyle rule violations were found. See the report at: file:///home/travis/build/SecUpwN/Android-IMSI-Catcher-Detector/AIMSICD/build/reports/checkstyle/main.html`

**Comment by SecUpwN** [comment]
@VladThodo, thanks for your work! @larsgrefer, do you know cause for the `checkstyle` violations?

**Comment by SecUpwN** [comment]
@VladThodo, I cannot find `file:///home/travis/build/SecUpwN/Android-IMSI-Catcher-Detector/AIMSICD/build/reports/checkstyle/main.html`, but Travis-CI actually lists the `checkstyle` [violations](https://travis-ci.org/SecUpwN/Android-IMSI-Catcher-Detector/builds/111396310#L1850-L2258).

**Comment by VladThodo** [comment]
@larsgrefer Problem solved :-)

**Comment by SecUpwN** [comment]
Appoved! Awesome work, guys! :smile_cat:

**Comment by SecUpwN** [comment]
Approved

**Pull request merged**
