### PR TITLE
added a tab strip across the main screen

### PR DESCRIPTION
**Pull request by tobykurien**
this makes it obvious that the page can be swiped

### CODE REVIEW

**Comment by tobykurien** [comment]
Screenshot of what this looks like:
device-2015-03-05-181641

**Comment by tobykurien** [comment]
Obviously, the activity title now seems like a duplicate, so I could change that back to "AIMSICD" if you like.

**Comment by SecUpwN** [comment]
Thanks for this neat clarification! @E3V3A shall I pull that in for the **Release** that I'm about to craft? Also please tell @tobykurien if he shall change the activity title or keep as proposed..

**Comment by E3V3A** [comment]
Yeah, I agree. In another app or app location, this would be perfect, but now it looks cluttered and redundant. People always try to swipe even when not possible. Another drawback is that on small screens this take up too much screen area. Sorry Toby, but I vote for not including this. I really like it as it was.

**Comment by SecUpwN** [comment]
Ok, @E3V3A, we will neglect this from being included in the current release. But the general idea is good, espscially when you say that people try to swipe even when not possible. @tobykurien isn't there another way to indicate "swipyness" even for tiny screens?

**Comment by E3V3A** [comment]
Come on guys! Why we're wasting time on this stuff? Isn't there any other more important issues to deal with? Perhaps have a look at [this](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/4e595dc2de82e57f8c1786b2097ebb6175eba6c5/app/src/main/java/com/SecUpwN/AIMSICD/service/CellTracker.java#L515-L517). How can I add the currently connected CID in there?

**Comment by SecUpwN** [comment]
@E3V3A, I understand that you think that this is "unncessary stuff", but actually it is great, for two reasons: First of all, it makes use of the Android design principles. We have swipe on certain places, not all. And if people get confused because we don't indicate were it is available, this is the fix for it. Secondly, it improves our UI/UX and thus is a step forward towards #258.

So my suggestion is: We're not going to throw this away, but maybe make the tab strip a little smaller (if even possible)? I'll gladly merge this when that happened and I'm sure you'll appreciate the new swipe indicator soon, @E3V3A. After this has been done we'll be right back in the detection stuff. Promised.

**Comment by E3V3A** [comment]
I don't need a swipe indicator, I need a detection indicator. ;)  I really hate this fluff that is keeping this thing from being minimalistic and functional. As you said yourself swiping is standard issue since JB, so dumb-shits who haven't figured that out by now, shouldn't even bother to use this app. If you really insist on a swipe indicator, then at least remove the text and keep the strip. We can also use the progress bar area for this same strip.

**Comment by tobykurien** [comment]
@E3V3A I found the lack of discoverability of the swipe view to be **amateurish**. Some views swipe, others don't, and this makes for a frustrating user experience. Android proivides two widgets to handle this specific scenario: tabs on the action bar at the top, or the tab strip that I implemented. The tab strip takes the least space and gives a clear indication of what you can swipe to, what is selected, and also allows you to click on the titles to switch. It's already smaller than the accepted minimum touch target size. An alternative solution is to use dots or lines (like on a homescreen), but that's not a standard control (hence way more work), and is better suited to things lke carousels and homescreens. Just have a look at Google Play, or any other major app on the Play store, and you will see that this is how it's done.

As for using up screen space - I'm testing this on a 3.7" screen and the content is vertically scrollable, so I don't see why this is even an issue.

As for why I "waste" time on this, rather than the things **you** specifically want, there are a few reasons:

- You almost always ask for things that goes against how Android is supposed to work, e.g. log tags, database versioning (you want to bypass this without understanding why it works the way it does), etc.
- You ask for things that add little to no value to the end user or app, but takes a disproportionally huge amount of effort, e.g. "truncate the gps coords" or "highlight changes on phone screen"
- You ask for things that can't be implemented or are difficult to implement because there isn't an Android API for it
- You ask for stuff that could take days to implement, rather than the hours I have to spare

So I looked through the list of Issues, decided that none of them were low-hanging fruit, and thought I'd fix one of the worst UX problems on the app currently.

**Comment by E3V3A** [comment]
Hi @tobykurien  
Thank you for giving me some constructive criticism. We all need that sometime. I probably can't respond to everything you said above. But let me try. 

I hear what you say about the swipe view, not being obvious. Yes, I like it, but then we have to solve the redundant labeling. Should we then remove the top bar with status icon? Or can we replace the text next to the status icon with something more informative like what we proposed in the widget in #278? We also discussed having first time detailed and graphic usage instructions in #181 and elsewhere. Do we really need all these instructions? 

Every time we add these things the app grows and become increasingly complex. We still don't have a clear understanding on how it works and where it is doing what it is doing. This is probably the greatest reason as to why I have such an opposing view of these things. If we actually understood how the app works and can document it. Then I'd have no problem adding whatever UI candy we can get our hands on, but until then, there is no surprise that developers are reluctant to join since it is just too much a of learning curve to understand what is doing what, without any documentation, and barely any comments on what code is doing what and where it is used. I'm in the process of learning this when my spare time allows and that is simply not good enough. 

> You almost always ask for things that goes against how Android is supposed to work, e.g. log tags, database versioning (you want to bypass this without understanding why it works the way it does), etc

This is probably correct since Android often fails on several of these items. If I don't understand it, it is probably because it doesn't make sense, or nobody bothered to explain it. (How I attempt to use the log tags make perfect sense, and now it is all nicely aligned and easy to find when viewing logcat, unlike the default and disorganized and often wrong TAGs I've found in the code.) 

> You ask for things that add little to no value to the end user or app, but takes a disproportionally huge amount of effort, e.g. "truncate the gps coords" or "highlight changes on phone screen"

I completely disagree there. I have no idea how you can say that it has little to no value to the end user, when I'm trying to minimize the amount of redundant text, and emphasize the important parts of the information content. At the same time you're mentioning this in the light of this particular issue where I'm trying to keep the development focused on the functional promise. I think what you just said above applies more to what we're trying to do in respect to this issue. Also truncating a real number is trivial! Highlighting sudden network changes, live on the screen, would be far more useful and directly applies to what this app is supposed to do, than swiping side ways to look in the database with a nice title....

> You ask for things that can't be implemented or are difficult to implement because there isn't an Android API for it

This is not a trivial project and we've made that clear from the very beginning. There is no API for catching IMSI-catchers and detecting spies in the network. I'm so sorry for this, so this is how it is, otherwise we are all free to go make a FlappyBird2. 

> You ask for stuff that could take days to implement, rather than the hours I have to spare

I understand, but there is no one pressuring you to do anything. (At least I am not.) So I'd much rather see developers spend a few extra days fixing actual issues and building a solid detection basis, than wanking for quick eye-candy. 

That being said, I appreciate very much what you have done and what you attempt to do, but I stand my ground to not lose focus of what this app is actually supposed to be doing, and what it is not.

**Comment by SecUpwN** [comment]
Good evening ladies and gentlemen. With great respect to both of you, I must say that seen from the outside, all this is a pretty messy kindergarten. Since we've had this sort of discussion before and lost developers through being stubborn while arguing with not losing the focus, I thought we've learned something from this, but apparently we didn't. So now I am taking the lead to remedy this situation:

1. Please **NEVER** ever discuss nasty stuff and "fights" outside of our internal chatrooms again!
2. What the heck to we have a `development` branch for if we cannot test PRs like this one?
3. If someone codes something, no matter how small the PR, we have learn to be THANKFUL!
4. All around the web we're stating that every single PR is welcome. This discussion is **senseless**!

@E3V3A, I've already sent you a pretty heavy E-Mail about this and I can totally understand how pissed you might be and highly likely are. Please do yourself a favor and take a few days off. It really does no good if we get too emotional here and start using words like "wanking". I really love both of you guys and I wish that both of you talk to each other via E-Mail about this to treat each other with respect again. We're all grown-up, right? @tobykurien is an awesome coder and I really do **NOT** want to lose him because simple navigation principles like this cannot be tested because we're "too focused" on the detections! So please guys, get yourself together and use the `development` branch what it is for.

I will re-open this PR and aim to **MERGE** this just to have the swipe indicator in our upcoming internal release and see how it works. Gosh, we can always revert the changes, so what is all the mocking around about anyways? @tobykurien please do me the small favor and try to find an answer for:

>Yes, I like it, but then we have to solve the redundant labeling. Should we then remove the top bar with status icon? Or can we replace the text next to the status icon with something more informative like what we proposed in the widget in #278? We also discussed having first time detailed and graphic usage instructions in #181 and elsewhere. Do we really need all these instructions?

This is it for now. I guess both of you are sick of it for the rest of the week, and you really should use that time to spend with friends and family. Have you heard me on that? I do **NOT** want any of of develop on here until **SUNDAY**. Take your time off, have a cocktail, breathe some fresh air, please. And yes guys, you may hate me for merging this once above questions are cleared and some small code updates have been added by Toby. I just want to have a look, so don't freak out. I promise that we'll focus on the core things after that again, I will add a pciture with the [new development/release cycle](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Development-Status) shortly.

**THANK YOU** to both of you for your **HARD WORK**, I know all this is a tough time, but please: Let's find the fun of our project again and let's treat each other like adults again. Have a fun time offline! :)

**Comment by tobykurien** [comment]
Hold on, don't merge yet, found a problem

**Pull request merged**
