### PR TITLE
Use a depencency injection

### PR DESCRIPTION
**Pull request by larsgrefer**
Introduce a dependency injection with the following features:
- `@InjectView`
  - inject views into Activities and Fragments (like Butterknife)
- Declare Menus and Layouts for Activities and Fragments via `@XmlLayout` and `@XmlMenu`
- `@InjectResource` and `@InjectAttribute`
  - inject Resources and Attributes in everything with a Context (Services, Activities, Fragments, ...)
- `@Inject`:
  - Inject custom objects (in this PR Loggers and OkHttpClients)

see: #570

### CODE REVIEW

**Comment by SecUpwN** [comment]
@larsgrefer, thanks for your steady pull requests! Please don't forget to add a description in the OP.

**Comment by larsgrefer** [comment]
@SecUpwN I'll provide more information when the PR is ready to merge

**Comment by larsgrefer** [comment]
@SecUpwN @DJaeger please review

**Comment by SecUpwN** [comment]
Thank you, @larsgrefer! Looks fine to me, waiting with the merge until @DJaeger replied.

**Comment by larsgrefer** [comment]
@SecUpwN Not waiting for @DJaeger ?

**Comment by SecUpwN** [comment]
>@SecUpwN Not waiting for @DJaeger ?

I would like to, but it seems he has not been online since several weeks and also does not reply on our repo when mentioned. Not sure where he is or if he is fed up by the way we manage our project.

**Pull request merged**
