### PR TITLE
Improved OCID upload

### PR DESCRIPTION
**Pull request by kairenken**
Finally after #333 and #334 this one is the one to use. I've done my changes on devbranchs now ;). Travis is fine for my fork. So I'm optimistic it will work now.

### CODE REVIEW

**Comment by E3V3A** [comment]
@kairenken  Great Job! Thanks a bundle! :)

**Comment by SecUpwN** [comment]
Thanks for your endurance, @kairenken! I have switched our default branch to `development` now using [these great instrcutions](https://help.github.com/articles/setting-the-default-branch/). All future pull requests should now be added correctly.

**Comment by kairenken** [comment]
Cool! But if I had read the manual, I would had less trouble. BTW do you have a mailing list or something like that for discussion about development?

**Comment by SecUpwN** [comment]
@kairenken, I will invite you to our internal developer chatroom. Give me a second..

**Pull request merged**
