### PR TITLE
Cleaned up SmsDetector.java implementation, related issues #615, #537

### PR DESCRIPTION
**Pull request by smarek**
So, what was done:

 - Removed unused class-global fields
 - Removed, WTF, code `new Thread().sleep(500);`
 - Rewritten implementation of reading String lines out of buffer, including one more local temporary variable
 - Fixed author javadoc tag
 - Replaced first level of `for-loop` in `checkForSilentSms` with `foreach` 
 - Removed pointless calls `toString()` in context like this `DETECTION_PHONENUM_SMS_DATA[2].toString()` (where DETECTION_PHONENUM_SMS_DATA is array of Strings)
Some encoding sincerely occured on-the-fly, hope you don't mind.

#615 discussion points are imho fixed by this PR
#537 pointed out that the problem with performance is in string retrieval/parsing/checking, I agree and we should imho migrate the code over to regexp declarations, and I'm worried we do not now correctly handle situations on border of string stream (where detection would fail because the data are incorrectly splitted by newline character)

### CODE REVIEW

**Comment by banjaxbanjo** [comment]
@smarek Thanks for modifying code and improving something similar to what my last PR was going to do. Nice to see someone helping out on detection because this is what the app is about.

**Comment by banjaxbanjo** [comment]
Also so from tests I done regexp seems very slow a bit like string format.

**Comment by SecUpwN** [comment]
I feel blessed to see you repsoning here, @banjaxbanjo. Since you've closed your important pull requests, do you think you could add your changes back again after I've merged this?

**Comment by banjaxbanjo** [comment]
@SecUpwN I will have a look at my offline dev sometime this week with original PR to see what can be merged. No promises😉

**Comment by SecUpwN** [comment]
>No promises

No need to promise anything, I hate promises but love honesty. ;-) Shall I merge the proposed changes?

**Comment by banjaxbanjo** [comment]
The offline class I have for sms detection is copy & paste the full class and uses a different method for reading buffer, Just needs minor formatting and its 10 times better than current class, be no problem to merge this PR by smarek but if I was to add the previous PR I would be overwriting this pr for it to work the way I intended. Can work behind scenes on class with smarek so we can finish this class for good.

**Comment by SecUpwN** [comment]
>Can work behind scenes on class with smarek so we can finish this class for good.

Would you really do that? This would be absolutely **lovely**! I guess @smarek can add the necessary changes to this PR so that it gets polished and does not have to be closed. Thanks and happy hacking! :)

**Comment by smarek** [comment]
@SecUpwN will try 

@banjaxbanjo please push your code somewhere online and let me know, i'll be happy to assist you to rebase it on top of latest dev (or maybe merge it with changes proposed by this PR).

**Comment by smarek** [comment]
Tracking info: https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/pull/619/commits
Merge from ca1e405e129891af4c1e1d24d77b96197a2e1d35 to c7647a842e2cee4059814ce14a4ae0e41658b4d4

**Comment by smarek** [comment]
So I've rebased the original PR#619 into second commit, to be clear about what has changed.
I've also refactored the code, fixed names in whole class, formatted the code, etc.

Please note, it's possible I've broken something with this rebase, so I'd be glad for testing from original author @banjaxbanjo and code review from anyone that's interested.

**Comment by smarek** [comment]
Also I've taken some of the feedback @agilob provided to original PR, and integrated it within (`checkForSms` method rewritten for optimized usage of `.split` call, handled possible incorrect detection string and `LOADED_DETECTION_STRINGS` finalized)

**Comment by SecUpwN** [comment]
Huge thanks to both of you @smarek and @banjaxbanjo for working behind the scenes to improve that important part of our code. I'll be waiting for @banjaxbanjo's green light here to merge this next week.

**Comment by banjaxbanjo** [comment]
@SecUpwN this is working smooth now please merge. Cheers @marek awesome merge job and nice coding.

**Comment by smarek** [comment]
Should I squash the commits so we don't spam the repo history?

**Comment by smarek** [comment]
Well I squashed them together, @banjaxbanjo thanks for testing and support in development
@SecUpwN now it's ready to be merged :+1:

**Comment by smarek** [comment]
@agilob thanks for feedback, is everything OK now? Give us please a your status, so we can merge it.

**Comment by banjaxbanjo** [comment]
@smarek Cheers for all the mods👍

**Comment by SecUpwN** [comment]
Waiting for the green light to merge this.

**Comment by smarek** [comment]
@SecUpwN I think we're good to go here, all @agilob comments were addressed in refactoring the commit, would be nice to end up with working sms detection again :+1:

**Comment by SecUpwN** [comment]
>...were addressed in refactoring the commit...

So is this the point were I should merge, or shall I wait? ;-)

**Comment by smarek** [comment]
I think we can merge it :smiling_imp:

**Pull request merged**
