### PR TITLE
Translation into Russian has been started 

### PR DESCRIPTION
**Pull request by DimaKoz**
also:
- Restored some strings of comments
- Increased timeout for server response

### CODE REVIEW

**Comment by DimaKoz** [comment]
A huge thanks to @agilob  for improving the translation into Polish.

**Comment by SecUpwN** [comment]
Thank you guys! German translations will be done by myself soon.
Should we add a menu `Language` in `Preferences/Interface Settings`?

**Comment by DimaKoz** [comment]
>Should we add a menu Language in Preferences/Interface Settings?

No. Language settings will be used from the phone settings.

**Comment by SecUpwN** [comment]
>No. Language settings will be used from the phone settings.

Fair. This will also avoid having more clutter in our app. Merging this now.

**Pull request merged**
