### PR TITLE
Calculate versionNames from git-tags

### PR DESCRIPTION
**Pull request by SecUpwN**
This pull request is aiming to calculate the `versionName` from git-tags. Before we can merge this, @ijansch needs to tell us here if the Issue with undetected `git` ([stacktrace](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/f23e9fe80e2abff03d536bcf48e06a86796bbea1#commitcomment-15168328)) has been resolved in Buildozer. @larsgrefer, would you please add a few arguments here why calculating them is better?

### CODE REVIEW

**Comment by larsgrefer** [comment]
The main argument for doing this is the dry principle.
We already maintain our releases with their specific names with git tags and github releases.

without this we have to keep the git tags and the version in the build.gradle in sync manually
with this the build.gradle just uses the last or current git tag as version

**Comment by SecUpwN** [comment]
Just to let you guys know, I have emailed @ijansch several days ago to update us on the current status here, yet he did not reply. Maybe @Buildozer can tell us what the current state of fixing the `git` Issue is?

**Comment by SecUpwN** [comment]
@larsgrefer, since our Buidozer builds now correctly display the GIT-SHA in the About-Screen, do you think this pull request is ready to be merged? Or do is there more work needed for this to be completed?

**Comment by SecUpwN** [comment]
@larsgrefer, are you ignoring me?

**Comment by larsgrefer** [comment]
I'm not sure about merging this PR because of #750

**Comment by SecUpwN** [comment]
@larsgrefer, me neither. I am pretty sure that #682 will make our lives easier, yet I still have to manually release our `normal` flavour to Aptoide (they wanted to provide me with their API documentation a month ago, I'll ask again today). But regarding this PR, is there any other advantage other than that our `build.gradle` uses the last or current git tag as version? Is there a better way respecting #750?

**Comment by SecUpwN** [comment]
Just found [paperwork](https://github.com/zsoltk/paperwork) by @zsoltk. Please see if it is helpful here.

**Comment by larsgrefer** [comment]
paperwork is a nice idea, but does not solve #750 

I've rebased this in order to resolve the merge conflicts and think we can merge it now

**Comment by SecUpwN** [comment]
>I've rebased this in order to resolve the merge conflicts and think we can merge it now

I guess I willthen have to manually update the F-Droid versions, huh? :P

**Comment by larsgrefer** [comment]
@SecUpwN We already have to update the versions manually now

**Comment by SecUpwN** [comment]
>We already have to update the versions manually now

Ok, I see. Last question before I merge this: What will our version update procedure look like afterwards?

**Comment by SecUpwN** [comment]
@larsgrefer?

**Comment by larsgrefer** [comment]
increase the versionCode and tag the commit

**Comment by SecUpwN** [comment]
>increase the versionCode and tag the commit

Thanks, @larsgrefer. Just for my own slow brain: That means when we push out a new version, I just have to write the `CHANGELOG`, push the changes via pull request to branch `master` and then create a new `RELEASE` with target `master` and then tag it properly like `v0.1.39-alpha` so that GitHub will properly increase our app `versionName` (and when #682 is merged also add the APK to the releases)?

**Comment by larsgrefer** [comment]
@SecUpwN exactly

At the moment there is a little difference between the tag names and the versionName, because the tag is prefixed with `v`. Please let me update this PR to be able to honor this, before we merge it

**Comment by SecUpwN** [comment]
>Please let me update this PR to be able to honor this, before we merge it

Shall I re-open this pull request then, or do you plan to remove branch `feature/autoVersion`?

**Comment by larsgrefer** [comment]
I'll reopen it once its ready

**Comment by SecUpwN** [comment]
>I'll reopen it once its ready

I hope you'll never quit development on our app, even though we have so many open Issues, slow development and too few developers working to make this app come true. Thanks for your heart blood!

**Comment by larsgrefer** [comment]
a tag named `vfoobar` will now result in a versionName `foobar`

**Comment by SecUpwN** [comment]
>a tag named `vfoobar` will now result in a versionName `foobar`

Why aren't we suing the `v` like we used to? I thought it was good like it is.

**Comment by SecUpwN** [comment]
@larsgrefer, if you'd answer my question above and rebase this PR, I will certainly merge it now. :)

**Comment by SecUpwN** [comment]
@larsgrefer, will https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/AIMSICD/build.gradle#L19 change automatically to the correct versio when I craft a new release on GitHub after having pushed all changes from branch `development` to branch `master`? I'm confused.

**Pull request merged**
