### PR TITLE
Cleaned up AIMSICDDbAdapter implementation

### PR DESCRIPTION
**Pull request by smarek**
+ Formatted code and comments
+ Replaced hard-coded database path with Context related path (it's the same, but allows repackaging and dev package extensions, etc..)
+ Finalized for performance purposes
+ Fixed few typos in logs
+ Removed unused field and class variables (mostly commented out)
+ Removed unnecessary `.toString()` calls
+ Avoided NPE on few Cursor usages
+ Updated `CommandResult` and `RequestTask` according to variable name changed

### CODE REVIEW

**Comment by smarek** [comment]
Also what's up with that excessive comment-based discussions? That's real mess, and I want to remove them all once we get to fix the DB layer implementation to provide objects and downgrade-upgrade procedures.

**Comment by SecUpwN** [comment]
>Also what's up with that excessive comment-based discussions?

One of the things E:V:A was fighting for, was to keep comments within the code so that developers could possibly continue already started code and understand existing code as well. But if you ask me, I think that we should *only* keep necessary code comments that are inevitable to understand difficult parts and make damn sure that code comments are following a common coding standard that does not clutter our code. I'd appreciate a fresh **Issue** for the code comment cleanup so that we can link PRs for that, too.

**Comment by He3556** [comment]
i am asking for a central documentation about the code, for a long time. So we all knew where the important things happen (detection) and get a overview about the classes. But it seems like nobody is interested. New developers might like it, when they start to work in this project.

**Comment by smarek** [comment]
@He3556 I'd like it as well, do you have any specific idea about that? Or if you haven't opened issue already, that would be cool :+1: Thanks

**Comment by banjaxbanjo** [comment]
Still a newbie when it comes to database and all comments where for EVA to understand what was happen as it was still in dev, I was kinda being pushed to finished this fast as it was holding up the project development since it was  tied to every other function. Got burnt out for coding this and left a good base to work out besides the errors and comments.

**Comment by SecUpwN** [comment]
>i am asking for a central documentation about the code, for a long time. So we all knew where the important things happen (detection) and get a overview about the classes. But it seems like nobody is interested. New developers might like it, when they start to work in this project.

@He3556, what about [General Overview](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/General-Overview) and [Technical Overview](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Technical-Overview)?

**Comment by smarek** [comment]
@SecUpwN this PR doesn't really touch the documentation, the question was reaction to observed state of code, so I don't think we need to stay put here

**Pull request merged**
