### PR TITLE
Repair OCIDCSV parsing

### PR DESCRIPTION
**Pull request by DJaeger**

### CODE REVIEW

**Comment by E3V3A** [comment]
Does this pass on Android studio for the api 17?

**Comment by E3V3A** [comment]
@SecUpwN please check this... I don't know what to do here... Merge and test or close?

**Comment by DJaeger** [comment]
It's crazy.
I dont know what to do to fix currently.
I will dig deeper and fix it.
Do NOT MERGE until Travis build succeed.

**Comment by agilob** [comment]
parseDouble throws an exception which isn't handled by your code. Change this line to and it will be fine.

```
            double number = 0;
            try {
                number = Double.parseDouble(String.valueOf(nf.parse(s).doubleValue()));
            } catch (ParseException e) {
                e.printStackTrace();
            }
```

**Comment by SecUpwN** [comment]
>I dont know what to do to fix currently.

Thanks for haninging in tight, @DJaeger! Please try to use the code above.

**Comment by SecUpwN** [comment]
Please don't hate me for chaising you around, @DJaeger. Please see [this](https://travis-ci.org/SecUpwN/Android-IMSI-Catcher-Detector/builds/69170674#L2062-L2066):

```JAVA
/home/travis/build/SecUpwN/Android-IMSI-Catcher-Detector/app/src/main/java/com/SecUpwN/AIMSICD/utils/OCIDCSV.java:89: error: cannot find symbol
} catch (ParseException e) {
^
symbol: class ParseException
location: class OCIDCSV.OCIDCSVLine
```

**Comment by agilob** [comment]
You need to add another import: `import java.text.ParseException;` Try compiling your code before committing and pushing.

**Comment by DJaeger** [comment]
@agilop: Sorry, but I don't have a IDE on mobile phone.
And as I work 95% with my mobile phone I can not compile bofore, so I use Travis as my compiler.

**Comment by DJaeger** [comment]
@marvinmarnold has changed these parts in the meantime...
As I can not repair merge conflicts on my mobile phone I have to wait until I am on my IDE.
Please be patient or do a PR yourself...

**Comment by SecUpwN** [comment]
>Please be patient or do a PR yourself...

Thanks you, we will be patient @DJaeger. ;-)

**Comment by SecUpwN** [comment]
>Please be patient or do a PR yourself...

Thank you, we will be patient @DJaeger. ;-)

**Comment by E3V3A** [comment]
> Sorry, but I don't have a IDE on mobile phone.
And as I work 95% with my mobile phone I can not compile bofore, so I use Travis as my compiler.

@DJaeger  This is a very dangerous developing method... AS (IDE) does a lot of additional checking that you'll probably miss...

**Comment by SecUpwN** [comment]
>Also Travis doesn't compile if we're running out of our weekly compile *quota*.

@E3V3A, as for the Travis CI limit you're right. But as for the CoverityScan limit I have been ranting about this to Travis CI and CoverityScan developers and we've then constructed code in a separate shell file that get's downloaded from our own SpiderOak account to make **Travis CI continue gracefully** even if the CoverityScan limit has been reached. This change had been added with https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/665885fd3806d38f78f5d9d406ca922145e059e1.

**Comment by DJaeger** [comment]
Moved to https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/pull/518.

**Pull request closed without merging**
