### PR TITLE
 Map Viewer UX issues #228 

### PR DESCRIPTION
**Pull request by DimaKoz**

### CODE REVIEW

**Comment by SecUpwN** [comment]
Thank you very much. Please also increase the version to `android:versionName="0.1.25-alpha-b43"`. When this has been added to the pull request, I will merge it. Which Issues are left after merging it?

**Comment by DimaKoz** [comment]
[E3V3A](https://github.com/E3V3A) wrote:
> Can we keep OSM data in a cache to reduce time? 

Ability of cache of tiles has been switched on

**Comment by SecUpwN** [comment]
>Ability of cache of tiles has been switched on

Perfect. Please increase the version as mentioned above and I'll merge this.

**Comment by E3V3A** [comment]
Awesome! Thanks @DimaKoz .

**Pull request merged**
