### PR TITLE
The menu has been reordered (starting to a preferred layout), issue SecUpwN/Android-IMSI-Catcher-Detector#258

### PR DESCRIPTION
**Pull request by DimaKoz**
@E3V3A wrote:

>Here I show the current menu versus the changes.

The menu has been reordered (starting to a preferred layout), issue SecUpwN/Android-IMSI-Catcher-Detector#258

Before:
menu_before_0
menu_before_1

Now:
menu_now_0
menu_now_1

### CODE REVIEW

**Comment by DimaKoz** [comment]
>The Travis CI build failed 
> Could not find com.android.support:support-v4:22.1.1.

Well, maybe this link will be useful, or me regain the old version of the library?
http://stackoverflow.com/a/18749565

**Comment by E3V3A** [comment]
Travis builds usually fails when our free weekly building quota is surpassed. Wait for a couple of days and it should be ok.

**Comment by DimaKoz** [comment]
@E3V3A  I think that the reason for this failure build a new version of the library - com.android.support:support-v4:22.1.1
Travis can not find the library in the file system, it confirms its log
https://travis-ci.org/SecUpwN/Android-IMSI-Catcher-Detector/builds/59965691#L1037

I could be wrong, but I see two solutions:
- Add a new version of the library for Travis;
- Switch back to using the old version of the source code (in my fork);

**Comment by SecUpwN** [comment]
>Add a new version of the library for Travis

@DimaKoz, if we can fix that with a simple change in our `.travis.yml`, let me know!

**Comment by DimaKoz** [comment]
@E3V3A 
>However, not sure this is the issue. (TL;DC.)

Why? What is wrong?

I did this issue according to the written description of you (as the start of the implementation of this issue https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/258 )
> 

screen_shot

I'll continue to do so in accordance with the description:
as E3V3A wrote:
> Here the symbols ==> means rename to this

@SecUpwN

**Comment by DimaKoz** [comment]
closed.

**Comment by E3V3A** [comment]
If there's a new library available, we should try to use it, **unless** it requires a later API (17) than we want to support. Does it?

**Comment by DimaKoz** [comment]
>If there's a new library available, we should try to use it, unless it requires a later API (17) than we want to support. Does it?

yeah
I probably fix it in the commit https://github.com/DimaKoz/Android-IMSI-Catcher-Detector/commit/7117eceb6536250c537b9761885c9d279a4c7738

**Pull request closed without merging**
