### PR TITLE
logging if no data available for upload + remove OCID_UPLOAD_PREF

### PR DESCRIPTION
**Pull request by kairenken**
I'm not sure how small pull requests should be. What do you prefer? Small or bigger onces. Here are some very small improvements on the upload function I found usefull myself.

### CODE REVIEW

**Comment by SecUpwN** [comment]
@kairenken, awesome to see you contributing regularly now! We don't care how small the pull request is, just that it is well documented and that you add [proper code comments](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/CONTRIBUTING.md#important-note-on-commits) so that other developers can see what has been done and may need fixing. So **THANKS** for this new PR, I would like to wait until @tobykurien had a look at it.

**Comment by kairenken** [comment]
@SecUpwN, thanks for the flowers ;) But my contributions are really small things yet. But I get deeper into the code more and more. I really like the project. I'm glad to help.

**Comment by E3V3A** [comment]
@kairenken  I think since we're more than one person working on various stuff, that it is better we try to make the PR's as small as possible. Because then it's more easy handle potential merge conflicts by manual adjustments. For example I had done some changes to both CellTracker and RequestTask last night, but didn't finish, and now we've got a pending merge conflict. But I will drop my own edits in favour of yours, but hope to avoid this in the future.

**Comment by tobykurien** [comment]
Sorry for the late response. Had a look, and it looks fine, although all it does is remove the use of a particular saved preference.

**Pull request merged**
