### PR TITLE
Fixes Comments in CellTracker

### PR DESCRIPTION
**Pull request by banjaxbanjo**

### CODE REVIEW

**Comment by DJaeger** [comment]
This is also not complete.
Why doyou merge @E3V3A?
...

**Comment by banjaxbanjo** [comment]
Fixes Comments @DJaeger what else is missing?

**Comment by DJaeger** [comment]
You have not fixed the reorderings and removed imports.
Maybe more.

**Comment by banjaxbanjo** [comment]
recording can you point be to code please?

**Comment by E3V3A** [comment]
OMG... Pfuuuhhh...
(I'm just merging all, I'm sick of reverting because, we'd have to go way back already.)

**Comment by banjaxbanjo** [comment]
Ok I'm on this unused imports comming up

**Comment by DJaeger** [comment]
@banjaxbanjo:
Please compare your commit with https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/d590e2ea774750d12177d9151d12ddf86b4b8b42 (as referenced multiple times by @E3V3A ...)

**Comment by DJaeger** [comment]
You have to repeat ALL changes of that commit, as you reverted them all!

**Comment by SecUpwN** [comment]
>(I'm just merging all, I'm sick of reverting because, we'd have to go way back already.)

Sounds like you didn't even check at all. From now on, we'll add a new rule here: Every larger pull request has to be checked by at least two developers before we merge it to avoid situations like this.

>You have to repeat ALL changes of that commit, as you reverted them all!

Really? Is there no other way to add another fix so that we get to a cleaner and more stable state?

**Comment by banjaxbanjo** [comment]
Guys this is going overboard all that appears to be wrong is a few comments missing/moved and misplaced, The code is functioning as usual, I can not spot anything else. We dont need line for line as original just useful comments that where missing

**Comment by SecUpwN** [comment]
>The code is functioning as usual, I can not spot anything else.

@banjaxbanjo, thanks for clarifying. I'll chill and hope you can take a break now. :palm_tree:

**Pull request merged**
