### PR TITLE
About Page update & Custom PopUp Class

### PR DESCRIPTION
**Pull request by banjaxbanjo**
Added a pop up class that can be used to create a basic popup with:
Title
Icon
Header
Data
Updated about page icons when click I detailed popup will appear with more info.

### CODE REVIEW

**Comment by SecUpwN** [comment]
@banjaxbanjo was it really your intention to close this one?

**Comment by banjaxbanjo** [comment]
Ya sec will make a new PR when I'm at computer with few minor changes.

**Comment by banjaxbanjo** [comment]
Ya m8 I closed it before you pushed it to make it easier for my next PR with changes Im making will make another PR with new changes asap when Im at my laptop

Cheers
Paul

Sent from Yahoo Mail on Android

**Comment by SecUpwN** [comment]
Thanks dude, I've just read all your mails. Don't give up!

**Pull request closed without merging**
