### PR TITLE
Versioning using GIT abbreviated commit ID

### LINKED ISSUE #147: Build: Automatic version and app name update with Gradle
Implement automatic build and version updates when using Travis-CI and Gradle, to build our App. 
The `build.gradle` script to do this, is described [HERE](http://bryankrosenbaum.com/2013/11/27/getting-to-know-gradle-auto-increment-version-and-signing-releases/), and lastest version can be found [HERE](https://github.com/bryanro/later-android/blob/master/Later/build.gradle). This would obviously require a few modifications in the *RegEx* as our build string is different, including changing the correct min/max of the supported API. (min=API-**17**, max=?) 

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
        package="com.SecUpwN.AIMSICD"
        android:versionCode="24"
        android:versionName="0.1.24-alpha-build-12">
```

The link above also provide a way to implement automatic APK signing, using a [signing.properties](https://github.com/bryanro/later-android/blob/master/signing.properties) file. 

And [HERE](http://toastdroid.com/2014/03/28/customizing-your-build-with-gradle/) is a way to automatically name the built APK. 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/5231067-build-automatic-version-and-app-name-update-with-gradle?utm_campaign=plugin&utm_content=tracker%2F565750&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F565750&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by smarek**
Using short form of current commit id and appending it to current, manifest defined, `versionName`

+ Edited reports to say if returning version code or name

```
> gradle assembleRelease -S
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
Importing with getManifestVersionCode()
Returning version code 36
Importing with getManifestVersionName()
Returning version name 0.1.36-alpha-0747dc5
```

This closes #147

### CODE REVIEW

**Comment by smarek** [comment]
This also removes need to change VersionName with provided PRs and commits, so that should easy up contribution cycle a bit

**Comment by SecUpwN** [comment]
>This also removes need to change VersionName with provided PRs and commits, so that should easy up contribution cycle a bit

Does it? I always changed that by hand to update our `CHANGELOG` properly. Does that change now?

**Comment by smarek** [comment]
Yes, you can refer to short commit ids in CHANGELOG to address that in similar manner imho

**Comment by SecUpwN** [comment]
>Yes, you can refer to short commit ids in CHANGELOG to address that in similar manner imho

Pretty neat change! But wouldn't that mean that I'd have to add a new entry in our `CHANGELOG` for every merged change in our repository? Sorry for asking so much, I'm just trying to find out how to do it.

**Comment by smarek** [comment]
Well every Release should be tagged with appropriate repository version anyway, version prefix (ie. `0.1.36-alpha`) doesn't change automatically, it's only the suffix `-commitid` which changes with repository changes.

This removes the need of step https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Development-Status#versioning

Raising manually versionCode when releasing is still needed. Name of release will be suffixed with commit-id from which it was built, so I'd recommend you to change versionCode, do a merge to master and then proceed with building Release APK

**Comment by SecUpwN** [comment]
>...so I'd recommend you to change versionCode, do a merge to master and then proceed with building Release APK

That's the way we're already doing it. Let's give it a shot, shall we, @He3556? ;-)

**Comment by smarek** [comment]
Want me to provide signing with config instructions through Gradle in separate PR for building releases?

**Comment by SecUpwN** [comment]
>Want me to provide signing with config instructions through Gradle in separate PR for building releases?

Not sure what you mean by that. Remember that we also have a [signing.properties](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/signing.properties) file, not sure you knew yet.

**Comment by SecUpwN** [comment]
>Want me to provide signing with config instructions through Gradle in separate PR for building releases?

Thanks for asking, I have talked to @He3556 about this and both of us agree that this is not necessary since others are needed to build signed releases, that's our job. Waiting for @He3556 to sign off the merge. ;-)

**Comment by SecUpwN** [comment]
@larsgrefer, this work seems to have vanished with #652. Are you able to re-enable it for better tracking?

**Comment by larsgrefer** [comment]
@SecUpwN It currently depends on where you build, on travis and your local machine is everything okay. On buildozer git ist not installed

**Comment by SecUpwN** [comment]
>On buildozer git ist not installed

Ok, then it seems to be an Issue with Buildozer. Will contact them. Case closed. ;-)

**Pull request merged**
