### PR TITLE
Fixed bug with doubling (tripling, etc.) markers on the map

### PR DESCRIPTION
**Pull request by DimaKoz**

### CODE REVIEW

**Comment by E3V3A** [comment]
It's always good to see what you mean with that...especially when there is no description of the issue. Perhaps a screen shot? (I.e. I didn't notice any bugs/issues that fits this title?) Are you trying to avoid clustering?

**Comment by SecUpwN** [comment]
>I didn't notice any bugs/issues that fits this title? Are you trying to avoid clustering? 

Thanks @DimaKoz! Waiting for these questions to be cleared before merging this.

**Comment by DimaKoz** [comment]
>I didn't notice any bugs/issues that fits this title?

This bug can be reproduced by clicking the download button on the map.
Each time number of markers to become more than on the amount of records in the DB (not cleaned from the array of old markers)

> Are you trying to avoid clustering? 

no, I do not try to fix it.
We still have a problem with some markers, as they have the same coordinates, and different CID.

**Comment by SecUpwN** [comment]
>This bug can be reproduced by clicking the download button on the map.

Bug has been confirmed, merging this pull request now.

**Comment by E3V3A** [comment]
@DimaKoz 
1. Same GPS co's but different CID is perfectly fine and very common as each cell tower may handle multiple providers, sectors and areas. 
2. I thought I had fixed that with the BTS cleanup routine after download. Same towers should be removed...AFAICR. Ah! Never, mind. Now I think understand what you're saying, the towers are not removed from map layer, probably because of caching. Try to clean map cache after re-downloading.

**Pull request merged**
