### PR TITLE
files of resources were renamed, 'about' fragment has been changed

### PR DESCRIPTION
**Pull request by DimaKoz**
device-2015-04-28-010115

### CODE REVIEW

**Comment by DimaKoz** [comment]
device-2015-04-28-010115

**Comment by agilob** [comment]
Could you change one more thing?
Class AIMSICD, lines: 309-310
```
Helpers.msgLong(mContext, mContext.getString(R.string.contacting_opencellid_for_data)
+ getString(R.string.this_might_take_a_minute));
```

Please remove the second getString, currently it shows:
`Contacting OpenCellID for data... This may take up to a minute. This may take up to a minute.`

Change to:
```
Helpers.msgLong(mContext, mContext.getString(R.string.contacting_opencellid_for_data));
```

It's my bad, I copied too much strings last time.

Thanks o/

**Comment by DimaKoz** [comment]
hi
sure


I found another hardcoding :(
Can I ask you to translate and send me more these lines?

    <string name="open_cell_id_button_cancel">Cancel</string>
    <string name="open_cell_id_button_ok">OK</string>
    <string name="about_desc_icon_idle">Idle / Loading.</string>
    <string name="about_desc_icon_active_tracking_near">Active tracking
close to you!</string>
    <string name="about_desc_icon_ok">Everything OK.</string>
    <string name="about_desc_icon_tracked_down">You are being tracked
down!</string>
    <string name="about_desc_icon_insecure_area">Insecure Service Area.
Leave it!</string>
    <string name="about_desc_icon_run">RUN! Handset manipulated!</string>
    <string name="about_desc_icon_title">Click Status Icons below for
Detailed Information</string>


2015-04-28 0:39 GMT+03:00 agilob <notifications@github.com>:

**Comment by SecUpwN** [comment]
Great work @DimaKoz! Have you received everything you needed now?

**Pull request merged**
