### PR TITLE
Repair OCIDCSV parsing

### PR DESCRIPTION
**Pull request by DJaeger**
Successor of https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/pull/510.
Should solve https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/325.

### CODE REVIEW

**Comment by DJaeger** [comment]
Great, this version works.

**Comment by SecUpwN** [comment]
Thanks for re-crafting this. How come that our app now crashes when downloading OCID data?

**Comment by DJaeger** [comment]
See #325

**Comment by E3V3A** [comment]
The app crashes after startup... So I really wanna know in which way it works for you, @DJaeger .

**Comment by DJaeger** [comment]
The app crashed before my PR since #516.
This PR does not fix the crash created in #516 but a parse error, which prevented all users with locales that use camma as decimal separator, from downloading BTS (OCID) data.
I couldn't test if my fix works, but I know what the methods I implemented do and as I have fixed my missings, typos and copy and paste failures, the build is now working, so my fix should work after fixing #516.

**Comment by marvinmarnold** [comment]
Is this fixed? If not I'd suggest moving from truncating to rounding. At a quick glance, [DecimalFormat](https://developer.android.com/reference/java/text/DecimalFormat.html) and [rounding](https://stackoverflow.com/questions/22833515/rounding-to-6-decimal-places-using-math-round-method-in-java-android) can handle the internationalization better than the current implementation.

**Pull request merged**
