### PR TITLE
EVEN MORE STRINGS TO TRANSLATE

### PR DESCRIPTION
**Pull request by agilob**
merged arrays.xml to strings.xml (only in values-XX), now translators
need to edit only one file values-XX/strings.xml

found more stupid strings in java code...

Now, translatable strings from arrays.xml are in strings.xml. All helpers are translated now. ufff.

@SecUpwN merged previous PR too quickly :<

### CODE REVIEW

**Comment by agilob** [comment]
I didn't increase version in manifest, nor edit wiki about translations. That commit message was supposed to be commit message not PR title ;)

**Comment by SecUpwN** [comment]
Dude, I can **REVERT** pull requests! Shall I do so?

**Comment by agilob** [comment]
Just merge this one, it's addition to the previous PR.

**Comment by SecUpwN** [comment]
>Just merge this one, it's addition to the previous PR.

Ok, I will do so. Please confirm the Buildozer invitation.

**Pull request merged**
