### PR TITLE
Added Buildozer Buildnumber to About View

### PR DESCRIPTION
**Pull request by DJaeger**
As requested here: https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/453

### CODE REVIEW

**Comment by E3V3A** [comment]
Why does this fail ??

**Comment by DJaeger** [comment]
Should not fail anymore, but have created a merge conflict, which I can not repair with my currently available git client.

**Comment by DJaeger** [comment]
Please reject this in favor of https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/pull/509.

**Comment by DJaeger** [comment]
Do it myself to not confuse someone.

**Pull request closed without merging**
