### PR TITLE
remove all permission which are not used

### LINKED ISSUE #636: Optimize system permissions
Delete unnecessary access, for example to the phonebook and other recourses we don't need. 
**EDIT by SecUpwN:** Also see [Stackoverflow: Clean up unused Android permissions]( http://stackoverflow.com/questions/18362305/clean-up-unused-android-permissions).

  

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28256326-optimize-system-permissions?utm_campaign=plugin&utm_content=tracker%2F565750&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F565750&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by larsgrefer**
accordingly to https://github.com/RomainPiel/AndroidPermissionsUsage

close #636

### CODE REVIEW

**Comment by SecUpwN** [comment]
@larsgrefer and @banjaxbanjo, please move the discussion of SMS detection to #537. My question is, can we *really* remove the permissions this PR deletes without losing current functionality of our app?

```JAVA
-    <uses-permission android:name="android.permission.INTERNET"/>
```
 If we remove this, will users still be able to use the buttons in the About-Menu?

```JAVA
-    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
```
If we remove this, will our app still start right after the boot has been completed?

```JAVA
-    <uses-permission android:name="android.permission.RECEIVE_SMS"/>
-    <uses-permission android:name="android.permission.RECEIVE_MMS"/>
-    <uses-permission android:name="android.permission.RECEIVE_WAP_PUSH"/>
```
If we remove those, will our app still be able to detect the message we can already detect?

```JAVA
-    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
```
If we remove this, is AIMSICD still able to show the alert window when an event happens?

```JAVA
-    <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
```
If we remove this, is our app still able to store settings from the settings menu?

**Comment by banjaxbanjo** [comment]
Sms detection doesn't require any permissions just root. Will will have to remove the broadcast receiver that gets normal incoming sms if you remove the sms permissions. 

Thats not a problem because that method never worked and never will work so removing them once broadcast receiver is disabled is ok.

**Comment by SecUpwN** [comment]
>Will will have to remove the broadcast receiver that gets normal incoming sms if you remove the sms permissions. 

@banjaxbanjo, would removing [these lines](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/clean/permissions/app/src/main/AndroidManifest.xml#L140-L147) work to accomplish this?

**Comment by banjaxbanjo** [comment]
@SecUpwN Yes that should cancel the broadcast receiver for quick fix. Code in receiver can be removed then whenever

**Comment by SecUpwN** [comment]
>Code in receiver can be removed then whenever

Can you link which files need to be cleaned and what exactly has to be done? I might do that tonight.

**Comment by banjaxbanjo** [comment]
This file @SecUpwN not sure I'd anything is linked it so should be ok to remove.

https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/src/main/java/com/SecUpwN/AIMSICD/receiver/SmsReceiver.java

**Comment by SecUpwN** [comment]
@larsgrefer, can we safely remove [SmsReceiver.java](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/src/main/java/com/SecUpwN/AIMSICD/receiver/SmsReceiver.java)? And @banjaxbanjo are you sure we can still detect silent SMS after removing it? After all, the SMS receiver class handles the SMS PDU data, doesn't it?

**Comment by banjaxbanjo** [comment]
@SecUpwN it's 100%  safe to remove sec and never did and never will detect anything.

All detection is based on logcat.

**Comment by SecUpwN** [comment]
>@SecUpwN it's 100% safe to remove sec and never did and never will detect anything.

@banjaxbanjo, after removing `SmsReceiver.java` somehow feel not well not having asked @smarek before doing so. He seems to have put quite some work into it. @smarek, is it OK having removed this?

**Comment by banjaxbanjo** [comment]
Sec that receiver has nothing to do with sms detection and its to high level code to intercept silent type sms.

All detection is logcat based.

Basically no broadcast gets sent if silent type sms so this receiver is pointless for now.

**Comment by banjaxbanjo** [comment]
Low level = baseband   < best
Mid level = logcat radio < all we can get for now
High level = broadcast receiver < bad doesn't get any anything only normal sms not silent.

**Pull request merged**
