### PR TITLE
Revert "Merge new translations, &c?"

### PR DESCRIPTION
**Pull request by SecUpwN**
Reverts SecUpwN/Android-IMSI-Catcher-Detector#611

### CODE REVIEW

**Comment by SecUpwN** [comment]
@TPS, I have reverted your pull request since you added it to `master`, but all pull requests have to be added to `development`. Also, please *refrain* from crafting any releases, this is **my** part. Thank you!

**Comment by TPS** [comment]
No harm meant. of course.… ☺

**Comment by SecUpwN** [comment]
>No harm meant. of course.… ☺

No worries. But if I got this right yu meant to push all the latest changes from `development` to `master` in order to "push another release", right? I am currently preparing our `CHANGELOG`. Stay tight, please.

**Comment by TPS** [comment]
I just was operating on the assumption that perhaps there hadn't been any releases because there hadn't been large enough code commits for a _major_ release.  I was just pointing out (perhaps not gently enough, I suppose) that even a _minor_ release would have a good impact. ☺

**Pull request merged**
