### PR TITLE
AtCommand Fragment -> Activity

### PR DESCRIPTION
**Pull request by larsgrefer**

### CODE REVIEW

**Comment by SecUpwN** [comment]
Thanks @larsgrefer! Please add a short description to the OP for why making it an Activity is better.

**Comment by SecUpwN** [comment]
Approved.

**Comment by agilob** [comment]
I'd like to know why your question from this PR was removed without getting answer and why this code which introduces regressions was merged:

1. Only main activity should be shown in "recent apps"
2. Use activities to manage fragments, good android practice which is listed in wiki is not followed https://github.com/futurice/android-best-practices#use-fragments-to-represent-a-ui-screen

**Comment by SecUpwN** [comment]
>I'd like to know why your question from this PR was removed without getting answer and why this code which introduces regressions was merged

Good evening @agilob, I knew you'd chime in. To answer your main question: Because I know that at times I am asking lazy questions instead of researching myself, but then later realizing what I did and knowing that questions like mine will knock off developers. Main reason why I deleted my question and merged this pull request was because we previously merged #697 for dependency injection and likely this will be useful in the `AT Command Interface`. I am sure @larsgrefer will be able to add a few more reasons here.

One more thing: Since you are actively monitoring our pull requests and how we go about development, please do me the favor and chime in **before** we merge stuff, adding your concerns and maybe even some code changes. I know you love our project and only want to see it succeed, but I currently feel a bit like you're only pointing with a finger at us. No rant, just my personal and very private feeling. Thanks for helping us!

**Comment by agilob** [comment]
>please do me the favor and chime in before we merge stuff

I saw your question so I was waiting for an answer. I don't have much time to come here regularly. Personally I would revert it, I would also revert DI... As it doesn't introduce anything good, like improves speed, UI, add functionality or anything. 

>but I currently feel a bit like you're only pointing with a finger at us

Please read and respond to my emails from August, September and December to learn more. You promised me to respond soon...

>I knew you'd chime in.

I'm still on your mail-list and I observe repo, mostly when I travel to/from work, so don't expect too much activity ;)

**Comment by SecUpwN** [comment]
>Please read and respond to my emails from July, August and October to learn more. You promised me to respond soon...

I am sorry not having responded, @agilob. Please send your questions in encrypted form again, I am back on my personal computer. As for the other PRs: Lets see if they really do "not improve anything".

**Pull request merged**
