### PR TITLE
descriptions of menu were improved

### PR DESCRIPTION
**Pull request by DimaKoz**
the current screen
device-2015-04-29-025706

### CODE REVIEW

**Comment by SecUpwN** [comment]
Rockin' and rollin'! :guitar: Waiting for Travis CI to give me green light..

**Comment by agilob** [comment]
remove that `.` after Restore database

**Comment by SecUpwN** [comment]
>remove that `.` after Restore database

Thanks for chiming in @agilob. Why is that `.` a problem for you? In fact, we have dots on every notification. Maybe @DimaKoz can shed some light on what the correct and preferred Android coding way is? In my eyes having the dots makes use of correct grammar. But if you can point me to the ight Android developer reference, I am very willing to remove the dots. As always: Pull requests correcting these things are very welcome, our code shall follow the preferred guidelines and best practices in coding.

**Comment by agilob** [comment]
In section `Settings`, there are 3 options, two of them don't have dot at the end, there is dot after `Restore database`.

**Comment by SecUpwN** [comment]
>In section `Settings`, there are 3 options, two of them don't have dot at the end, there is dot after `Restore database`.

@agilob, thanks for clarifying! Will be fixed in a minute. ;-)

**Pull request merged**
