### PR TITLE
Db Update

### PR DESCRIPTION
**Pull request by banjaxbanjo**
There is still a few things I would like to sort on this but I am merging now so not to slow down progress of project.

New DB will stay open and be closed on app exit so open and close not need if you want to access db.

Cheers @marvinmarnold for bts_mearsure layout and stuff.

I'm sure this fixes alot of issues but @E3V3A will have to go over and select which ones are solved.

New db is pre-complied and copied from assets folder when app is first install (This will throw an error on first create and is part of the code so dont worry about it)

if you want to add or update the database use http://sqlitebrowser.org/ and then copy it back into assets folder.

IMPORTANT: delete/uninstall your AIMSICD app before installing this or it wont work.

Still stuff I want to remove like the try catch blocks in restoreDB() in AIMSICDDbAdapter but leaving there for now and will update later so we can check for null pointers.

Too much code here to comment on what I changed.

SignalStrenghtTracker needs to be updated for new DB so its not accessing db atm till I sort it. (Minor for now)

Changing lac/cell not in OCID and detected sms now sent to eventlog.

Shit load of work here so if any devs spot something please fix for me as I've put a crap load of time into this and haven't got the time to go over every little detail.

Cheers

### CODE REVIEW

**Comment by banjaxbanjo** [comment]
Is this another Travis CI issue😐

The command "./gradlew connectedAndroidTest --info" exited with 1.

**Comment by E3V3A** [comment]
It's green so I'll merge...

**Comment by banjaxbanjo** [comment]
Cool. WIP but alot done and stable from my testing and nothing major.

**Comment by E3V3A** [comment]
Seem stable...

**Comment by SecUpwN** [comment]
@banjaxbanjo, @marvinmarnold and @E3V3A: You guys are heroes! :crown:

**Comment by banjaxbanjo** [comment]
Awesome  I'm sure something will pop up but least now be have something to move forward  with. It just needs to be tweeked and make it more advanced. Will will spot new things to work on now that new tables are in place.

**Pull request merged**
