### PR TITLE
Table in database viewer will be loaded automatically without clicking on the button

### PR DESCRIPTION
**Pull request by agilob**
1. removed button
2. simplified code(?), onCreate is a bit longer now, but it's easier to follow the design as two nested classes were removed.
3. UI is more intuitive (for me?), user doesn't have to click on the button to load table with measures/cells/etc

screenshot_2015-05-20-19-01-10

### CODE REVIEW

**Comment by agilob** [comment]
I don't know why my PRs have your commits here @SecUpwN? I do
`git checkout upstream/master; git pull upstream master` should I use `development` instead of `master` to avoid it?

**Comment by SecUpwN** [comment]
It is because your local base seems to be out off sync. The best thing you can do, is to use [SmartGit](http://www.syntevo.com/smartgit/) and do a fresh **pull** before changing the code, then changing it locally, then **push** to a new branch or commit directly. Thus, you can avoid all the nasty shit. Regarding this awesome pull request, I guess you'd just need to increase the version to `03` so that I can merge it (we are at `02` now). Please do so. Thank you!

**Comment by agilob** [comment]
>do a fresh pull before changing the code, then changing it locally, then push to a new branch or commit directly.

That's what I do.

**Comment by agilob** [comment]
You can just cherrypick the first commit and 20b03af , all other commits are useless -.-'

**Pull request merged**
