### PR TITLE
Use a logging interface

### PR DESCRIPTION
**Pull request by larsgrefer**
not ready to merge yet

### CODE REVIEW

**Comment by SecUpwN** [comment]
@larsgrefer, when pressing `Debugging` in our app the log appears. What are you trying to do?

**Comment by larsgrefer** [comment]
Don't use `android.util.Log` directly, but use an Interface + android-specific Implemenation

just have a look at the diff

**Comment by SecUpwN** [comment]
>just have a look at the diff

I did, it now makes sense: You're just changing the way we log stuff, displaying it stays the same.
I'm granting permission to you to merge this whenever you feel it is ready. See ya later, aligator!

**Comment by SecUpwN** [comment]
Since branch `feature/logging` still exists, could you also have a look at #201, #208 and #583? Thanks!

**Pull request merged**
