### PR TITLE
Fixing missing navigation items

### PR DESCRIPTION
**Pull request by mattgraham**
This will fix your missing navigation items. In your code base nav was removed on mobile devices; in the original only specific items were hidden. 

Enjoy!

### CODE REVIEW

**Comment by E3V3A** [comment]
@SecUpwN What is this? Is this Wiki stuff or app related?

**Comment by DJaeger** [comment]
It's for the website

**Comment by SecUpwN** [comment]
@E3V3A, this appears to be a *misplaced* fix for my filed Issue https://github.com/mattgraham/midnight/issues/7.

Thanks for digging this, @mattgraham! But since I generate our website using the automatic page generator through GitHub pages, I guess you need to contribute this fix to the @GitHub codebase. It does not make much sense adding it to our pages branch, it will be gone with the next generated update.

**Comment by E3V3A** [comment]
@SecUpwN  Maybe we should just cancel this PR then? 
(It seem to be out of our hands and not related to our app.)

**Comment by DJaeger** [comment]
I think we should at least wait for a response of @mattgraham, why he opened this PR here and not for the @Github codebase.

**Comment by SecUpwN** [comment]
>Maybe we should just cancel this PR then? 

@E3V3A, here is what I previously stated:

>Let me know how you're aiming to solve my filed Issue with them, I will then close this.

Means: I am just waiting for his response here so that I know how he aims to fix this.

**Comment by mattgraham** [comment]
I've messaged Cameron about pushing my update to the original gh-pages theme. I no longer work at GitHub so I'm not sure what they'll want to do. Either way you can close this PR if you'd like; I've never used the gh-pages theme updates so I personally just add updates as I need them. Either way, its up to you; should they respond back I'll attempt to get it in the master codebase but I can't promise anything on that end anymore. 

Cheers!

**Comment by SecUpwN** [comment]
>I've messaged Cameron about pushing my update to the original gh-pages theme.

Thanks for having the balls to do so, @mattgraham! Even though the work you did with this pull request may vanish with the next generation of our website, I decided to merge and test it. Keep rockin'! :guitar:

**Pull request merged**
