### PR TITLE
Images has been compressed

### PR DESCRIPTION
**Pull request by DimaKoz**

### CODE REVIEW

**Comment by SecUpwN** [comment]
Thanks for the pull request, @DimaKoz! How did you compress the images?

**Comment by banjaxbanjo** [comment]
Looks goods to me @SecUpwN, I havent really looked at much of the database code in the project but I think this sorts the issue of not having duplicates of the same cell in the db. You'll have to get a second opinion from one of the guys that worked on this class. 

#297 is the progress bar issue @SecUpwN dont think this sovles that?

**Comment by E3V3A** [comment]
Progress bar issues has nothing to do with this. See my new comment in that issue.

**Comment by SecUpwN** [comment]
>#297 is the progress bar issue @SecUpwN dont think this solves that?

Yep, I already noticed. @tobykurien as crafted a fix for it with https://github.com/tobykurien/Android-IMSI-Catcher-Detector/commit/339b6e1b1829331e005e5364a10c7a987f2ed956. Expecting his PR.

**Pull request merged**
