### PR TITLE
Tiny mod to Sms Detection

### PR DESCRIPTION
**Pull request by banjaxbanjo**
I tried a lot of different versions of reading from buffer and this
method seems to work the best even though aligob doesn't think its good.

Will experiment with others when I get to the time to create a new
method for reading buffer effectively that will work with detection.

### CODE REVIEW

**Comment by SecUpwN** [comment]
Too bad I cannot merge this. Did you delete your repo and quit development? :(

**Comment by tvgurududehd** [comment]
Code is saved to a zip @SecUpwN if someone wants to merge into current code and update what needs changing I can email build.

**Comment by banjaxbanjo** [comment]
Code is saved to a zip @SecUpwN if someone wants to merge into current code and update what needs changing I can email build.

**Comment by SecUpwN** [comment]
Thanks for answering. Did you quit development, @banjaxbanjo?

**Comment by banjaxbanjo** [comment]
Sent you email on that sec😉

**Pull request closed without merging**
