### PR TITLE
About redesign with new icons and cleaned up aboutfrag code.

### PR DESCRIPTION
**Pull request by banjaxbanjo**
If you like this merge it m8 here is a screen shot
http://postimg.org/image/7x66u3ac9/

### CODE REVIEW

**Comment by SecUpwN** [comment]
@banjaxbanjo, thanks you very much! It looks great, but does it change anything about the other external links? Also, I liked that we only had Icons for the actual Status Icons. @He3556 what do you say?

**Comment by banjaxbanjo** [comment]
Doesn't do anything about the external links but its better looking than the standard buttons. External Links will be a WIP m8.

**Comment by He3556** [comment]
for me it looks fine. thx banjaxbanjo, good work :)

**Comment by He3556** [comment]
should we wait with the new release until we have changed the hyperlinks to pop up windows?

**Comment by banjaxbanjo** [comment]
This isn't a major issue anyway guys so pop ups can be a WIP.

**Comment by He3556** [comment]
ok, than i would guess we wait with a new release - no need to hurry.

**Comment by SecUpwN** [comment]
Thanks for the neat discussion here, @He3556 and @banjaxbanjo. Don't get me wrong, but I don't quite see the improvements with the latest changes proposed here. It is an interesting design change, but in my eyes I like the previous and already merged changes more. I thought #174 would be fixed now - the buttons with the external links to `Changelog`, `License` and such is fine with me, or do you see this as aproblem if AIMSICD accesses an external IP when those buttons are being pressed?

Furthermore, and this has been discussed with @He3556 internally, we should change the text of the Status `MEDIUM`. could you please elaborate on that please, @He3556? What to do with this PR now?

**Comment by banjaxbanjo** [comment]
The previous design was ok  m8 but the buttons looked very basic and if your going for a polished finish icons would be the way to go. Its ok of you dont like m8 I wont be offended but I will use this for my personal copy😉

**Comment by He3556** [comment]
we need to change the text for the yellow thread icon. we have the problem that most of the times there are Cell IDs missing from the OCID download. So if there are Cell IDs that are not in the OCID we get the yellow status. But there is no thread only a lack of data. So we need to change the text on the about page to "still exploring to gather more information". than we also need to change the text in the other parts in the code.

**Comment by SecUpwN** [comment]
@banjaxbanjo, sorry for closing this a little too fast, I re-edited my response above. I know you like the new Icons, but with more Icons, we add more confusion. The main focus shall still be the Status Icons, otherwise the user just gets a "boom" into his face and likely closes the About-Tab again because it is just too much color and fancy stuff. I love it the way it is right now, I hope you're going to use **our** "personal copy". :smiley_cat: Thank you for not getting offended that I closed it. Difficult decision man.

**Comment by banjaxbanjo** [comment]
Hey Mate,
All is good mate I just thought it needed a facelift:) I get what your saying about Just having that status icons so they draw people to them, it would be an easy fix to put a red border to highlight them. If you look at it I really just replaced the buttons with icons and put the text there so they know what they are for. 

Anyway mate its ok I like this stuff to see what I could achieve and new coding skills etc..
CheersPaul
 


     On Saturday, 21 March 2015, 1:23:00, Security: Pwned. <notifications@github.com> wrote:
   

 @banjaxbanjo, sorry for closing this a little too fast, I re-edited my response above. I know you like the new Icons, but with more Icons, we add more confusion. The main focus shall still be the Status Icons, otherwise the user just gets a "boom" into his face and likely closes the About-Tab again because it is just too much color and fancy stuff. I love it the way it is right now, I hope you're going to use our "personal copy".  Thank you for not getting offended that I closed it. Difficult decision man.—

**Comment by He3556** [comment]
sorry mate - forget the new text for the yellow icon. i was to fast with this. we will fix this in another way so we can leave the old text like it is

**Pull request closed without merging**
