### PR TITLE
French translation (ready to merge)

### PR DESCRIPTION
**Pull request by gusfl**
I translated all strings to french (french is my mothertongue)

...and i have some (additional) questions : 

- **tracking vs monitoring** : what is the difference exactly? 

- **"2G network lock" option -> why?** as far as i know (i'm wrong? ^^), 2G network are unsecure, because they have a poor encryption (compared to UMTS/LTE), or no encryption at all. If the app is used to avoid IMSI catchers, it shoud contrariwise force avoiding 2G only network, right ? i don't understand.

- **what is a "silent voice SMS"?** A...SMS who contain voice (wtf?)? If it's *a sms witch is not displayed when recived*, what is the difference between a class-0 sms and a silent voice SMS? There are two strings called ```alert_silent_sms_detected``` and ```alert_silent_voice_sms_detected``` in ```translatable_strings.xml```. What's the difference between them?

### CODE REVIEW

**Comment by E3V3A** [comment]
Hello @gusfl ! Thanks for translating. 

> *Tracking* Vs. *Monitoring*

1. God question! Monitoring is really a bad name artifact of an on/off button for AIMSICD, whereas *tracking* refers to saving the BTS data and looking for fake BTSs.

2. AIMSICD is meant to detect fake BTS not avoid them, although a future implementation should be able to do that as well.

3. "silent voice SMS", please make a PR, and remove or change the "voice" part. It doesn't make sense. `class-0 =/= type-0` SMS. One *can* be seen, the other cannot (from API).

For other details, please read all our documentation and related issue threads.

**Comment by banjaxbanjo** [comment]
Hey, I didnt really Know the technical term of this message when coding and being lazy I let it stick, if you look in detection strings you will see voice mail indicator thats what I went off at the time so it has some relation to why I named it that. Technical name is MWI

http://en.m.wikipedia.org/wiki/Message-waiting_indicator

**Comment by SecUpwN** [comment]
Good morning @gusfl, thank you so much for adding your translations! Your pull request is especially important since IMSI-Catchers have been used in France extensively lately as well and I will merge it as soon as I have cleared up a few more questions. Please stay patient until then, thank you.

@banjaxbanjo, thanks for adding a link to what you actually meant with the "silent voice SMS". I have seen that `HushSMS` is able to send MWI messages to play a prank on users thinking that there would be a waiting message on their inbox, even though that is not the case. So what we're actually detecting, is if someone tried to play a prank on our phone? Does this type of message get sent by government agencies or other tactical forces? I am currently trying to find a better translation for this detecting as well as the corresponding alert since it is **not** a type-0 message. Or is it? @E3V3A, I would appreciate your wisdom on this since I'll have to update all translations and likely the menu descriptions as well.

**Comment by banjaxbanjo** [comment]
@SecUpwN if they know that alot of apps are only looking out of type 0 they will use alternatives and this maybe one it wouldnt be a good idea to take this out or any type of silent sms. As far as I know every sms asks for a location update so these could be used for the same effect as a type0. This and any another type of silent sms can be used to show if a user is on a certain cell by linking a tmsi to phone number if the network doesnt change tmsi often,so it can be used for tracking.

**Comment by SecUpwN** [comment]
>...it wouldnt be a good idea to take this out or any type of silent sms...

@banjaxbanjo, I never meant to take anything out, but just want these things to be named properly across all translation files. So would you suggest that I rename the translations to `MWI message`?

**Comment by gusfl** [comment]
thank you @banjaxbanjo for your explanation. Your feature is really usefull, anyway maybe we could add an option in settings "warn on MMI messages" or not? (because i think everyone does not necessarily want to receive a notification "Alert !" when he just receive a voice message). But i don't know if this would be a good idea (because it could be a big security issue)...

For the translation : i wrote (in french) something like "Voicemail Control SMS (MMI) Detected". Tell me if you have a better english sentence, so that I can translate it.

Also, sorry for the confusion between type-0 and class-0 sms. I made it because a lot of french (or even english) media/articles confuse them(it's not the first time i heard "class-0 are silent SMS"). Maybe it shoud be added a sentence on wiki or in the app like "type-0 SMS shoud not be confused with class-0 SMS. First is a silent text message, second is a flash text message witch is not stored on your phone"?

**Comment by SecUpwN** [comment]
>EDIT : what's wrong with travis?

Don't worry about it, @gusfl. I just added `leakcanary` and have to figure out what went wrong. ;-)

**Comment by banjaxbanjo** [comment]
@gusfl I dont know if new phones use this type of sms when receiving a voice mail but would be a good idea to test and see does a standard voice mail set this off. Cheers for translation

**Pull request merged**
