### PR TITLE
build a system app too

### PR DESCRIPTION
**Pull request by larsgrefer**
a bit gradle magic inspired by https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/674#issuecomment-163032708

@agilob 
@Copperhead

### CODE REVIEW

**Comment by SecUpwN** [comment]
@larsgrefer, what is this doing when merging? Does it enable our app to also work as a system app, or does this actually build a second app? As far as I know, @Copperhead is currently providing our app via the preinstalled version from the F-Droid store, thus they do not have to maintain updates. I'd like to keep it that way.

**Comment by larsgrefer** [comment]
The current app declares a bunch of system-app permissions but the following lines are disabled:
```xml
<!-- If we ever wanna make this a system app, we can add the following 2 lines above:
    coreApp="true"
    android:sharedUserId="android.uid.system"> -->
```
With this PR we will have one product flavor with all the system-app permissions AND the two lines enabled. And a second product flavor without both.

Currently gradle builds:
- `app-debug.apk`
- `app-release.apk`

With this PR gradle will build:
- `app-normal-debug.apk`
- `app-normal-release.apk`
- `app-system-debug.apk`
- `app-system-release.apk`

**Comment by SecUpwN** [comment]
>With this PR we will have one product flavor with all the system-app permissions AND the two lines enabled. And a second product flavor without both.

Thanks for explaining. Why can't we add those system permissions without building a second app? I mean, since most users install our app via Aptoide, F-Droid or direkt download from GitHub, I'm not sure why we need two apps. I guess this is related to #658.

**Comment by larsgrefer** [comment]
@SecUpwN why have you already merged this?
I wonder how buildozer will react :smiley:

**Comment by SecUpwN** [comment]
>@SecUpwN why have you already merged this?

Because you haven't reacted since 2 days and I thought you might be annoyed of my questions? ;-)

>I wonder how buildozer will react :smiley:

Worked beuatifully. Thanks for continuing your improvements!

**Comment by larsgrefer** [comment]
But which apk is delivered by Buildozer?

**Comment by SecUpwN** [comment]
I think it's `app-debug.apk`. Can you verify this from [this logfile](https://defuse.ca/b/mUJ0TzYo)?

**Comment by larsgrefer** [comment]
The is no `app-debug.apk` anymore but `app-normal-debug.apk` and `app-system-debug.apk`

The log does not tell what file is used.

in the worst case buildozer uses an old `app-debug.apk` from the project cache

**Comment by SecUpwN** [comment]
>in the worst case buildozer uses an old `app-debug.apk` from the project cache

I don't think so. They once told me that all data is being deleted after building the APK.

**Comment by larsgrefer** [comment]
Just have a look at the first 5 and last 5 lines of the log you posted

**Comment by SecUpwN** [comment]
>Just have a look at the first 5 and last 5 lines of the log you posted

Looks like our app is being built from cache. But I'll be waiting for their reply anyhow. Stay tuned.

**Pull request merged**
