### PR TITLE
DB update raw query

### LINKED ISSUE #550: Remove DBTableColumnIds.java and re-insert constants in Db adapter
Transparency has been totally lost in latest DB update (overhaul) PR. We need to re-insert all the DB constants in clear-text into the AIMSICDDbAdapter.java file and remove DBTableColumnIds.java. 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/24340337-remove-dbtablecolumnids-java-and-re-insert-constants-in-db-adapter?utm_campaign=plugin&utm_content=tracker%2F565750&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F565750&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by banjaxbanjo**
Changed code to old style of SQL queries

Tested as much as I could and all tables in DBV seem to work and look right.
Silent sms detection working and inserting in Eventlog.

BackupDB() RestoreDB() db tested and working.

Get OCID data with my own key(Entered Manually)  working. (Not working with Drawer Menu to
get OCID key) This problem is here before my PR.

Fixes #550

### CODE REVIEW

**Comment by SecUpwN** [comment]
Thanks you so much! Is this meant to fix #549?

**Comment by banjaxbanjo** [comment]
@SecUpwN these code was not created by me and not working only thing I changed was the table name and left rest because these columns are not in DBi_bts. @E3V3A will have to tell you with issue this fixes. Cheers

There appears to be a bug in delete detected sms in prefs menu but this has nothing to do with this PR. I'll be looking into this next.

```Java
        return mDb.query( DBTableColumnIds.DBI_BTS_TABLE_NAME,
                new String[]{"Mcc", "Mnc", "Lac", "CellID", "Lng", "Lat", "Signal", "Timestamp",
                        "Accuracy", "Speed", "Direction", "NetworkType"}, "OCID_SUBMITTED <> 1",//<-- where we getting these tables OCID_SUBMITTED DBi_bts?/DBi_measure?/DBe_import?
                null, null, null, null
        );
```

**Comment by SecUpwN** [comment]
Perfect. @DJaeger, would you please "approve" to merge this?

**Comment by E3V3A** [comment]
Hi Guys! Great job again, sorry I'm on the move and can't do much now, nor respond. Since yesterday the app was broken (both OCID download and get OCID key caused FC) for me, so hopefully this PR will help or fix. (Yes, it's been much more than 2 weeks since I last had to get an OCID key.)

> (Not working with Drawer Menu to get OCID key) This problem is here before my PR.

Did anyone file an issue for this? @SecUpwN Can you file one please?

BTW. Looking at the logcat, the new OCID key **is** actually returned, but then the app crashes, due to some http error: 

```
E/OpenCellIDActivity(...): Content has been consumed
```

**Comment by banjaxbanjo** [comment]
@E3V3A I think this OCID issue is open already #543

**Comment by E3V3A** [comment]
@banjaxbanjo  No that's different. There are 2 issues, one to download and one to get the key.

**Comment by banjaxbanjo** [comment]
@E3V3A ah okay but if you enter key manually it downloads okay for me with this current dev.

**Comment by SecUpwN** [comment]
> (Not working with Drawer Menu to get OCID key)
>Did anyone file an issue for this?

Not yet, because as far as I know the key needs to be requested via `Preferences` first?

@banjaxbanjo, please increase the version number like always so that we can merge this.

**Comment by banjaxbanjo** [comment]
@SecUpwN I tried increasing version with last pr and it would leave me but I will try now

**Comment by agilob** [comment]
@E3V3A execute() was moved to line 42 and to separate class.

**Pull request merged**
